### ISSUE TITLE
Module prototype : Create new module on ubuntu 

### ISSUE THREAD

**Issue by oitsuki** [OCA/server-tools#105]
Maxime

Loïc, did you put an accent in your module name ? Please try not to and report an issue to:

No, no accent.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/prototype/wizard/prototype_module_export.py", line 85, in action_export
    zip_details = self.zip_files(prototype.generate_files())
  File "/usr/lib/python2.7/dist-packages/openerp/addons/prototype/wizard/prototype_module_export.py", line 119, in zip_files
    target.writestr(info, filecontent)
  File "/usr/lib/python2.7/zipfile.py", line 1234, in writestr
    zinfo.CRC = crc32(bytes) & 0xffffffff       # CRC-32 checksum
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 1106: ordinal not in range(128)
```

**Comment by max3903** [comment]
ping @foutoucour

**Comment by foutoucour** [comment]
Hey @oitsuki,

Do you remember the string that you used?

Cheers,
J

**Comment by oitsuki** [comment]
I downloaded the latest development, seems work.

**Comment by foutoucour** [comment]
Cool.

Do you think we can close the issue?

Jordi

connecting people

**Comment by oitsuki** [comment]
yes you can.
Tk
