### ISSUE TITLE
[10.0]mass_editing. Search fields by model

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/server-tools#1068]
When searching  ir.model.fields records (for example on Settings > Database Structure > Fields) by model, got an error on this line: https://github.com/OCA/server-tools/blob/10.0/mass_editing/models/ir_model_fields.py#L19

Steps to reproduce: Go to Settings > Database Structure > Fields and search for model product.template. Got the following: `ValueError: invalid literal for int() with base 10: 'roduct.templat'`

**Comment by astirpe** [comment]
I got the same error on 11.0 (porting still in progress...).
See traceback in https://github.com/OCA/server-ux/pull/5#issuecomment-356583258

**Comment by astirpe** [comment]
Just tried, with commit https://github.com/AlceConsorcio/server-ux/commit/a6bb2dcabca3d82a4585e095b0b5120eca01b4ed, the error does not occur anymore.

**Comment by ivantodorovich** [comment]
Also present in `9.0`

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/extra-addons/odoo-enterprise/web/controllers/main.py", line 919, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/extra-addons/odoo-enterprise/web/controllers/main.py", line 911, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/extra-addons/ingadhoc-odoo-saas/saas_client/models/ir_model.py", line 15, in write
    return super(IrModel, self).write(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 173, in write
    return super(ir_model,self).write(cr, user, ids, vals, context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3855, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4013, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 826, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 492, in create
    if not self.search(cr, user, [('model_id','=',vals['relation']), ('name','=',vals['relation_field']), ('ttype','=','many2one')]):
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/extra-addons/oca-server-tools/mass_editing/models/ir_model_fields.py", line 18, in search
    map(int, domain[2][1:-1].split(',')))]
ValueError: invalid literal for int() with base 10: '_hr.employee.training.lin'
```

**Comment by rafaelbn** [comment]
Hello!! @aheficent @astirpe @ivantodorovich 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- https://github.com/OCA/server-tools/pull/848
- https://github.com/OCA/server-tools/pull/849 
- https://github.com/OCA/server-tools/pull/786

Thanks

**Comment by rafaelbn** [comment]
Hello!! @aheficent @astirpe @ivantodorovich 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- [x] https://github.com/OCA/server-tools/pull/848
- [x] https://github.com/OCA/server-tools/pull/849
- [ ] https://github.com/OCA/server-tools/pull/786
- [ ] https://github.com/OCA/server-tools/pull/1209

Thanks

**Comment by ivantodorovich** [comment]
@jjscarafia maybe you are interested in this, too, since I belive you already fixed this for `9.0`

**Comment by rafaelbn** [comment]
Your are really welcome for a :beer: @jjscarafia :smile:

**Comment by rafaelbn** [comment]
More fixes for mass editing: https://github.com/OCA/server-tools/pull/1209

**Comment by rafaelbn** [comment]
https://github.com/OCA/server-tools/pull/848 is merged! :grinning:

**Comment by rafaelbn** [comment]
https://github.com/OCA/server-tools/pull/849 is merged! :clap:

**Comment by NL66278** [comment]
Encountered this bug too:
Traceback (most recent call last):
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/addons/web/controllers/main.py", line 837, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/addons/web/controllers/main.py", line 859, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/models.py", line 4707, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/server-tools/mass_editing/models/ir_model_fields.py", line 19, in search
    map(int, domain[2][1:-1].split(',')))]
ValueError: invalid literal for int() with base 10: 'nalyti'

**Comment by NL66278** [comment]
I looked at PR #849 (the one for 10.0). Despite the description of the PR it did not change anything in ir_model_fields.py where the error occurs, so it is no surprise that the problem is not solved.

**Comment by alexis-via** [comment]
I confirm the bug is still present in v10 with up-to-date code from origin/10.0 :(
