### ISSUE TITLE
Traceback in audit log read rule

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-tools#1179]
Hi,

When adding a read rule we get a traceback when opening a record:
```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/customer/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/customer/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/customer/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/customer/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/customer/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/customer/odoo/odoo/api.py", line 678, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/opt/odoo/customer/odoo/odoo/models.py", line 4889, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 20; 2 is required
```

Thank you.
Cas

**Comment by rockcesar** [comment]
I have the same problem. My error shows:



Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-10-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-10-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-10-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-10-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-10-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-10-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-10-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-10-server/addons/web/controllers/main.py", line 891, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-10-server/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-10-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-10-server/odoo/api.py", line 678, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/odoo/odoo-10-server/odoo/models.py", line 4912, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 9; 2 is required

**Comment by rockcesar** [comment]
Greetings from GlobalManager, Chile. The code of auditlog is adapted to previous versions of Odoo, not completely to Odoo 10.0.

I have fixed it. The way in which it was reading the data, was wrong for Odoo 10.0. In the file auditlog/models/rule.py, change the method _make_read, for this one:

    @api.multi
    def _make_read(self):
        """Instanciate a read method that log its calls."""
        self.ensure_one()
        log_type = self.log_type

        @api.multi
        def read(self, fields=None, load='_classic_read'):
            result = read.origin(self, fields, load)
            # Sometimes the result is not a list but a dictionary
            # Also, we can not modify the current result as it will break calls
            result2 = result
            if not isinstance(result2, list):
                result2 = [result]
            read_values = dict((d['id'], d) for d in result2)
            # Old API
            if self and isinstance(self.env.cr, sql_db.Cursor):
                cr, uid, ids = self.env.cr, self.env.uid, self.ids
                if isinstance(ids, (int, long)):
                    ids = [ids]
                # If the call came from auditlog itself, skip logging:
                # avoid logs on `read` produced by auditlog during internal
                # processing: read data of relevant records, 'ir.model',
                # 'ir.model.fields'... (no interest in logging such operations)
                if self.env.context.get('context', {}).get('auditlog_disabled'):
                    return result
                env = api.Environment(cr, uid, {'auditlog_disabled': True})
                rule_model = env['auditlog.rule']
                rule_model.sudo().with_context({'auditlog_disabled': True}).create_logs(
                    env.uid, self._name, ids,
                    'read', read_values, None, {'log_type': log_type})
            # New API
            else:
                # If the call came from auditlog itself, skip logging:
                # avoid logs on `read` produced by auditlog during internal
                # processing: read data of relevant records, 'ir.model',
                # 'ir.model.fields'... (no interest in logging such operations)
                if self.env.context.get('auditlog_disabled'):
                    return result
                self = self.with_context(auditlog_disabled=True)
                rule_model = self.env['auditlog.rule']
                rule_model.sudo().create_logs(
                    self.env.uid, self._name, self.ids,
                    'read', read_values, None, {'log_type': log_type})
            return result
        return read

**Comment by GlobalManager** [comment]
You can watch the module fixed here:

https://github.com/GlobalManager/odoo-addons

**Comment by GlobalManager** [comment]
@pedrobaeza Hello, look at this module, if it fit for the OCA necessities. We fixed some code:

https://github.com/GlobalManager/odoo-addons/tree/10.0/auditlog

**Comment by pedrobaeza** [comment]
Please propose the patch as a PR following https://odoo-community.org/page/code

**Comment by GlobalManager** [comment]
Done, we did the pull request:

https://github.com/OCA/server-tools/pull/1259
