### ISSUE TITLE
Mass Update v11: NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by buzzy3** [OCA/server-tools#1220]
Installed on Enterprise v11:
model product

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 4995, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 4891, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo11/custom_addons/mass_editing/models/mass_object.py", line 47, in _onchange_model_id
    inherits_model_list = model_obj.search([('model', 'in', keys)])
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 1407, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 3674, in _search
    query = self._where_calc(args)
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 3471, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/usr/lib/python3.6/site-packages/odoo/osv/expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "/usr/lib/python3.6/site-packages/odoo/osv/expression.py", line 1214, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('model', 'in', dict_keys(['product.template']))

product.template

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 872, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 894, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3.6/site-packages/odoo/models.py", line 4123, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo11/custom_addons/mass_editing/models/ir_model_fields.py", line 16, in search
    isinstance(domain[2], basestring) and
NameError: name 'basestring' is not defined

**Comment by Garamotte** [comment]
It should work better with the version that has been migrated to v11: https://github.com/OCA/server-ux/tree/11.0/mass_editing

Please don't open an issue for a version when using code from another version.

**Comment by whalbauer** [comment]
I got the same error message "name 'basestring' is not defined" using v11 of mass_editing. Is this the problem:

basestring is no longer available in Python 3. From What’s New In Python 3.0:

The builtin basestring abstract type was removed. Use str instead. The str and bytes types don’t have functionality enough in common to warrant a shared base class. The 2to3 tool (see below) replaces every occurrence of basestring with str.

**Comment by qupro** [comment]
I think that confussion cames from the fact that app in
https://www.odoo.com/apps/modules/11.0/mass_editing_v11 (with basestring error)
seems to be the same that in 
https://github.com/OCA/server-ux/tree/11.0/mass_editing/ (works fine)
I downloaded the first one and I was near to put the issue same here by error.
