### ISSUE TITLE
auth_admin_passkey error when opening general settings with missing PR from 8, 9

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/server-tools#1227]
Dears,
why below merged commit in 8 and 9 by akretion avoided in v10 ?
https://github.com/OCA/server-tools/pull/519

The auth_admin_passkey is having bug in v10 since 4-5 months as below:
when opening general settings menu the passkey module through below error:
```
 Traceback (most recent call last):
  File "/opt/O10/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/O10/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/O10/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/O10/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/O10/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/O10/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/O10/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/O10/odoo/odoo/addons/web/controllers/main.py", line 891, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/O10/odoo/odoo/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/O10/odoo/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/O10/odoo/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/O10/odoo/odoo/odoo/addons/base/res/res_config.py", line 508, in default_get
    res.update(getattr(self, method)(fields))
  File "/opt/O10/.enabled/auth_admin_passkey/models/res_config.py", line 18, in get_default_auth_admin_passkey_send_to_admin
    'auth_admin_passkey.send_to_admin', 'True')),
TypeError: 'module' object is not callable
```

updating with the mentioned PR fixes the problem.

I will propose PR against 10.0 to this module.

ping @pedrobaeza

Regards,

**Comment by mohamedhagag** [comment]
PR created https://github.com/OCA/server-tools/pull/1228

**Comment by pedrobaeza** [comment]
Closing as there's PR.
