### ISSUE TITLE
[8.0] Mass Editing Tool: ValueError: invalid literal for int() with base 10: 'erkau'

### ISSUE THREAD

**Issue by msteinfeld-intero** [OCA/server-tools#124]
Go to Settings -> Database -> Technical -> Database Structure -> Fields

Search for Model "Verkauf" / "Sale"

Failure is thrown.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 859, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5060, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/server-tools/mass_editing/models/ir_model_fields.py", line 37, in search
    ('model_id', 'in', map(int, domain[2][1:-1].split(',')))
ValueError: invalid literal for int() with base 10: 'erkau'
```

**Comment by bwrsandman** [comment]
What language is your interface in?

Looks like the model is sending `erkau` where an int in string form is expected

**Comment by msteinfeld-intero** [comment]
The Interface is in german.

**Comment by intero-chz** [comment]
domain[2][1:-1] is 'erkau' in this example
'erkau'.split(',') is 'erkau' 
parsing this to int won't work.

Maybe the search was overridden to use it for mass_editing functionality, but it won't work with typical input anymore.

I will look into this, when i have time.

**Comment by flotho** [comment]
Hi,

Having the same issue here. I try to reache sale.order fields by filtering on model and have this message :

```
 File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5158, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/additional_repos/OCA-server-tools/mass_editing/models/ir_model_fields.py", line 38, in search
    ('model_id', 'in', map(int, domain[2][1:-1].split(',')))
ValueError: invalid literal for int() with base 10: 'ale.orde'
```

Additionnlly, the value set in the filter is sale.order and not `ale.orde`

**Comment by astirpe** [comment]
Same issue here while filtering by models.
