### ISSUE TITLE
Rompe la configuración y muestra página en blanco sin siquiera instalarla

### ISSUE THREAD

**Issue by ruslanguns** [OCA/server-tools#1303]
**Reproducción del problema:**

- Copiar directorio "mass_editing_v11" en el la carpeta /mnt/extra-addons_data/ 
- Al ir a reinciar servicios Odoo y sin siquiera instalar la app, la app de Odoo se muestra en blanco.

Al eliminar la carpeta se quita el problema.

**Error que lanza el log:**

```
2018-06-26 16:44:54,696 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1319, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 7, in <module>

  File "/mnt/extra-addons/mass_editing_v11/tests/__init__.py", line 5, in <module>
    from . import test_mass_editing
  File "/mnt/extra-addons/mass_editing_v11/tests/test_mass_editing.py", line 9, in <module>
    from odoo.addons.mass_editing.hooks import uninstall_hook
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'mass_editing'
```

**Comment by pedrobaeza** [comment]
You should always write in English in these repositories. Pleasy try latest version in server-ux.

**Comment by ruslanguns** [comment]
Sure! thanks!

**Comment by ruslanguns** [comment]
@pedrobaeza do you know where it's the auto-backup now? it isn't at the Server-ux repo now

**Comment by pedrobaeza** [comment]
https://github.com/OCA/server-tools/tree/11.0/auto_backup

**Comment by ruslanguns** [comment]
Thank you bro !!
