### ISSUE TITLE
"NameError: name 'basestring' is not defined" when adding fields

### ISSUE THREAD

**Issue by redlabmedia** [OCA/server-tools#1318]
mass_editing_v11 11.0.1.1.0

Odoo 11.0 (Community Edition)

When trying to "Add an Item" under Fields.  (Module: Contact)

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 873, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/addons/web/controllers/main.py", line 895, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo/odoo/models.py", line 4218, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo/addons/mass_editing_v11/models/ir_model_fields.py", line 16, in search
    isinstance(domain[2], basestring) and
NameError: name 'basestring' is not defined
```

**Comment by astirpe** [comment]
Module mass_editing for V11 is in another repository: https://github.com/OCA/server-ux
Try that one.
The version of the module you are using is not even existing in OCA.
