### ISSUE TITLE
auto_backup 11.0 - Stop Backup

### ISSUE THREAD

**Issue by antrax131** [OCA/server-tools#1351]
Hi,
after upgrading odoo server and server-tools the 27th of August my server does not back up, i have this error:
`Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fde262db470>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/auto_backup/models/db_backup.py", line 146, in action_backup
    for rec in self.filtered(lambda r: r.method == "local"):
  File "/odoo/odoo-server/odoo/models.py", line 4540, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/odoo/odoo-server/odoo/models.py", line 4540, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/odoo/custom/addons/auto_backup/models/db_backup.py", line 146, in <lambda>
    for rec in self.filtered(lambda r: r.method == "local"):
  File "/odoo/odoo-server/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/odoo/odoo-server/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/odoo/odoo-server/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/odoo/odoo-server/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column db_backup.backup_format does not exist
LINE 1: ...last_post","db_backup"."sftp_port" as "sftp_port","db_backup...
                                                             ^`
How can solve this?

**Comment by pedrobaeza** [comment]
You have to upgrade the module in your DB.

**Comment by antrax131** [comment]
Solved!!
