### ISSUE TITLE
Invalid domain term error in mass editing v11

### ISSUE THREAD

**Issue by elevationO** [OCA/server-tools#1362]
I am able to install the module but get this error when choosing the Model in the settings.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 5095, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 4990, in _onchange_eval
    method_res = method(self)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/mass_editing/models/mass_object.py", line 47, in _onchange_model_id
    @api.multi
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 3769, in _search
    query = self._where_calc(args)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 3566, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/osv/expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/osv/expression.py", line 1214, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('model', 'in', dict_keys(['product.template']))

**Comment by pedrobaeza** [comment]
Try to replicate the problem in runbot (https://runbot.odoo-community.org/runbot/250/11.0 - admin/admin). I would bet it's due to Bitnami stuff...

**Comment by elevationO** [comment]
I just tried the runbot and it worked fine.  I also just installed on a localhost v11ce I installed yesterday and get the same error.

When downloading the zip and extracting the folder is named "mass_editing_v11" and throws an error on the install.  I changed the folder to "mass_editing" like it shows in runbot and the module installs.

Could the renaming be part of the problem?

Thanks for your help

**Comment by pedrobaeza** [comment]
Yeah, the module directory should be `mass_editing`, not `mass_editing_v11`.

**Comment by elevationO** [comment]
Ok yes by changing it I was able to install as mentioned above. After installing on a fresh odoo 11ce I get this error.  

Can you help identify the error?

This was closed without a solution.

**Comment by pedrobaeza** [comment]
This is not a problem of the module, but your deployment.
