### ISSUE TITLE
[10.0-11.0] SSL error on tests run in Odoo.sh

### ISSUE THREAD

**Issue by carlosrve** [OCA/server-tools#1386]
When I create a new blank project in Odoo.sh v10, and add the OCA/server-tools as a submodule, the build failed with this error:

Failed to remove existing timezone info /home/machines/ubuntu-16.04/etc/localtime in container: Read-only file system
Host and machine ids are equal (ed55b77ba3633bc584825aba1e8a657e): refusing to link journals
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo-bin", line 5, in <module>
__import__('pkg_resources').declare_namespace('odoo.addons')
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2160, in declare_namespace
declare_namespace(parent)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2176, in declare_namespace
_handle_ns(packageName, path_item)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2111, in _handle_ns
loader.load_module(packageName)
File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
mod = imp.load_module(fullname, self.file, self.filename, self.etc)
File "/home/odoo/src/odoo/odoo/__init__.py", line 81, in <module>
import cli
File "/home/odoo/src/odoo/odoo/cli/__init__.py", line 9, in <module>
import deploy
File "/home/odoo/src/odoo/odoo/cli/deploy.py", line 5, in <module>
import requests
File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
from urllib3.contrib import pyopenssl
File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
import OpenSSL.SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Process returned error code 1.

This is due because there is not pyopenssl library installed on the execution environment. The requirements.txt is missing the dependency.

**Comment by carlosrve** [comment]
On v11 it is the same problem. I am creating a new PR for v11.
