### ISSUE TITLE
BASE_NAME_SEARCH_IMPROVED Throws Error on Filtering in APPS

### ISSUE THREAD

**Issue by agent-z28** [OCA/server-tools#1428]
2018-11-16 07:54:52,644 16536 ERROR tms odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo-11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo-11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo-11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo-11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-11/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo-11/addons/web/controllers/main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo-11/odoo/models.py", line 4222, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo-11/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo-11/odoo/models.py", line 3773, in _search
    query = self._where_calc(args)
  File "/opt/odoo-11/odoo/models.py", line 3563, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo-11/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/opt/odoo-11/odoo/osv/expression.py", line 1064, in parse
    push(create_substitution_leaf(leaf, _get_expression(comodel, left, right, operator), model))
  File "/opt/odoo-11/odoo/osv/expression.py", line 1057, in _get_expression
    res_ids = [x[0] for x in comodel.with_context(active_test=False).name_search(right, [], operator, limit=None)]
  File "/opt/projects/submodules/server-tools/base_name_search_improved/models/ir_model.py", line 68, in name_search
    self, base_domain + domain, res, limit)
  File "/opt/projects/submodules/server-tools/base_name_search_improved/models/ir_model.py", line 24, in _extend_name_results
    if result_count < limit:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by pedrobaeza** [comment]
@dreispt you were the original author of this. It needs a clause like `if limit and result_count < limit:`

**Comment by agent-z28** [comment]
it is odoo version 11

**Comment by dreispt** [comment]
I'm not sure where the problem is.
I'm aware that this feature dos not work on numeric fields, is that the case @agenterp ?

**Comment by andres-pcg** [comment]
@dreispt @pedrobaeza i'm having the same issue when searching for in_invoice on account.invoice model

**Comment by andres-pcg** [comment]
Any update on this one ?

**Comment by Vassy** [comment]
Same error on Odoo 11 CE, any suggestions?

**Comment by agent-z28** [comment]
Yes its just a Small change in the if condition 

--- a/base_name_search_improved/models/ir_model.py
+++ b/base_name_search_improved/models/ir_model.py
@@ -19,7 +19,7 @@ def _get_rec_names(self):
 
 def _extend_name_results(self, domain, results, limit):
     result_count = len(results)
-    if result_count < limit:
+    if limit and result_count < limit:
         domain += [('id', 'not in', [x[0] for x in results])]
         recs = self.search(domain, limit=limit - result_count)
         results.extend(recs.name_get())


Mit freundlichen Grüßen

We look forward to see you. Best Regards

Dipl. Ing. (Fh) Georg Notter

Agent ERP GmbH

www.agenterp.com

**Comment by agenterp** [comment]
-    if result_count < limit:
+    if limit and result_count < limit:

**Comment by ghost** [comment]
> Yes its just a Small change in the if condition
> […](#)
> --- a/base_name_search_improved/models/ir_model.py +++ b/base_name_search_improved/models/ir_model.py @@ -19,7 +19,7 @@ def _get_rec_names(self): def _extend_name_results(self, domain, results, limit): result_count = len(results) - if result_count < limit: + if limit and result_count < limit: domain += [('id', 'not in', [x[0] for x in results])] recs = self.search(domain, limit=limit - result_count) results.extend(recs.name_get()) Mit freundlichen Grüßen We look forward to see you. Best Regards Dipl. Ing. (Fh) Georg Notter Agent ERP GmbH [www.agenterp.com](http://www.agenterp.com)
> Am 13.01.2019 um 11:51 schrieb Vassil Toumbev ***@***.***>: Same error on Odoo 11 CE, any suggestions? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
Did the change in if condition fixed the issue for you?

**Comment by agent-z28** [comment]
@alfadil yes of course
