### ISSUE TITLE
Mass Editing v11 when adding fields

### ISSUE THREAD

**Issue by specitsystems** [OCA/server-tools#1464]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/odoo/odoo-server/odoo/models.py", line 4223, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/addons/mass_editing_v11/models/ir_model_fields.py", line 16, in search
    isinstance(domain[2], basestring) and
NameError: name 'basestring' is not defined

**Comment by pedrobaeza** [comment]
Are you using this with Python 3? Python 2 is not supported.

**Comment by pedrobaeza** [comment]
And another thing: are you using the proper module in https://github.com/OCA/server-ux/tree/11.0/mass_editing? Why are you publishing the issue here and not in that repo?

**Comment by specitsystems** [comment]
I think I have the wrong copy. apologies for posting on the wrong platform

**Comment by pedrobaeza** [comment]
Please check the proper one and try again, and if the problem persists, go to the right repo and put the issue there.
