### ISSUE TITLE
odoo server error

### ISSUE THREAD

**Issue by maryadimar** [OCA/server-tools#1473]
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 412, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 486, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 200, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/opt/odoo/addons/base_user_role/hooks.py", line 8, in post_init_hook
    env['res.groups'].update_user_groups_view()
  File "/opt/odoo/addons/base_user_role/models/res_groups.py", line 17, in update_user_groups_view
    res = super(ResGroups, self).update_user_groups_view()
AttributeError: 'super' object has no attribute 'update_user_groups_view'

**Comment by maryadimar** [comment]
I try install base_user_role v.10

**Comment by pedrobaeza** [comment]
This seems something on your deployment. If you check on runbot, it's working.
