### ISSUE TITLE
v11.0 database_cleanup Odoo server error !

### ISSUE THREAD

**Issue by m3asmi** [OCA/server-tools#1534]
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 57, in get_wizard_action
    wizard = self.create({})
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 93, in create
    return super(PurgeWizard, self).create(values)
  File "/opt/odoo/odoo11/odoo/models.py", line 3371, in create
    vals = self._add_missing_default_values(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1602, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 43, in default_get
    res['purge_line_ids'] = self.find()
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_modules.py", line 77, in find
    purge_lines.purge()
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_modules.py", line 54, in purge
    modules.unlink()
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 317, in unlink
    return super(Module, self).unlink()
  File "/opt/odoo/odoo11/odoo/models.py", line 2952, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "module" violates not-null constraint
DETAIL:  Failing row contains (1182, hr_payslip_input_salary_rule_rel_hr_salary_rule_id_fkey, null, 362, null, f, 2019-01-26 15:46:34.198773, 2019-01-26 15:46:34.198773, null, null, null, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."ir_model_constraint" SET "module" = NULL WHERE $1 OPERATOR(pg_catalog.=) "module""


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1231, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 554, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo/odoo11/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 430, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 57, in get_wizard_action
    wizard = self.create({})
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 93, in create
    return super(PurgeWizard, self).create(values)
  File "/opt/odoo/odoo11/odoo/models.py", line 3371, in create
    vals = self._add_missing_default_values(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1602, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_wizard.py", line 43, in default_get
    res['purge_line_ids'] = self.find()
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_modules.py", line 77, in find
    purge_lines.purge()
  File "/opt/odoo/qs/custom/database_cleanup/models/purge_modules.py", line 54, in purge
    modules.unlink()
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 317, in unlink
    return super(Module, self).unlink()
  File "/opt/odoo/odoo11/odoo/models.py", line 2952, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'psycopg2.IntegrityError'>: "null value in column "module" violates not-null constraint
DETAIL:  Failing row contains (1182, hr_payslip_input_salary_rule_rel_hr_salary_rule_id_fkey, null, 362, null, f, 2019-01-26 15:46:34.198773, 2019-01-26 15:46:34.198773, null, null, null, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."ir_model_constraint" SET "module" = NULL WHERE $1 OPERATOR(pg_catalog.=) "module""
" while evaluating
"action = env.get('cleanup.purge.wizard.module').get_wizard_action()"
```

**Comment by thomaspaulb** [comment]
Getting this also, but in v10 and with the column `name` of `mrp.production`.

```
psycopg2.IntegrityError: null value in column "module" violates not-null constraint
DETAIL:  Failing row contains (3176, null, null, null, null, 2017-06-27 17:33:51.769496, 2017-06-27 17:33:51.769496, null, 432, u, mrp_production_name_uniq, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."ir_model_constraint" SET "module" = NULL WHERE $1 OPERATOR(pg_catalog.=) "module""
```
