### ISSUE TITLE
fetchmail_attach_from_folder: command CLOSE illegal in state AUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by guewen** [OCA/server-tools#161]
Here is a traceback I got with the fetchmail_attach_from_folder installed when I clicked on the "Test & Confirm" button on a fetchmail (IMAP + SSL) server.

```
Traceback (most recent call last):
  File "/srv/openerp/parts/server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/parts/server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/parts/server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/parts/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/parts/server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/parts/server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/parts/server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/parts/server/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/openerp/parts/server/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/parts/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/parts/server-tools/fetchmail_attach_from_folder/model/fetchmail_server.py", line 72, in fetch_mail
    connection.close()
  File "/usr/lib/python2.7/imaplib.py", line 382, in close
    typ, dat = self._simple_command('CLOSE')
  File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 825, in _command
    ', '.join(Commands[name])))
error: command CLOSE illegal in state AUTH, only allowed in states SELECTED
```

I didn't investigated further because I didn't planned to use the module: it got installed automatically (fixed now in #156).

**Comment by hbrunn** [comment]
looking into this in #247, closing this
