### ISSUE TITLE
[12.0] Auditlog traceback

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-tools#1619]
Traceback when creating an object (invoice in this case);

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 135, in create_invoices
    sale_orders.action_invoice_create()
  File "/home/odoo/src/odoo/addons/sale/models/sale.py", line 542, in action_invoice_create
    invoice = inv_obj.create(inv_data)
  File "<decorator-gen-407>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/addons/base_automation/models/base_automation.py", line 228, in create
    records = create.origin(self.with_env(actions.env), vals_list, **kw)
  File "/home/odoo/src/user/community/auditlog/models/rule.py", line 230, in create_fast
    vals2 = dict(vals)
ValueError: dictionary update sequence element #0 has length 16; 2 is required
```

**Comment by StefanRijnhart** [comment]
Thanks for the report! Closing because the fix is merged now.
