### ISSUE TITLE
database_cleanup: KeyError: u'process.transition.action'

### ISSUE THREAD

**Issue by welshjf** [OCA/server-tools#163]
After doing a 7.0 to 8.0 migration with OpenUpgrade, I was left with two obsolete modules installed, "process" and "account_report_company". I installed database_cleanup, tried to purge them, and got this error:

```
Traceback (most recent call last):
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/jwelsh/foss/odoo/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/jwelsh/foss/odoo/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jwelsh/foss/odoo/server-tools/database_cleanup/model/purge_wizard.py", line 59, in purge_all
    context=context)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jwelsh/foss/odoo/server-tools/database_cleanup/model/purge_modules.py", line 53, in purge
    _db, _pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/pooler.py", line 46, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/modules/loading.py", line 423, in load_modules
    registry['ir.module.module'].module_uninstall(cr, SUPERUSER_ID, modules_to_remove.values())
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 462, in module_uninstall
    ir_model_data._module_data_uninstall(cr, uid, modules_to_remove, context)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1217, in _module_data_uninstall
    ir_model_constraint._module_data_uninstall(cr, uid, constraint_ids, context)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 575, in _module_data_uninstall
    model_obj = self.pool[model]
  File "/home/jwelsh/.local/lib/python2.7/site-packages/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'process.transition.action'
```

**Comment by gurneyalex** [comment]
@welshjf @hbrunn do you know if this is still relevant?

**Comment by welshjf** [comment]
I would assume the problem has not solved itself, however it is no longer relevant to me personally. Should be fairly easy to replicate (see discussion in OpenUpgrade#285).

**Comment by hbrunn** [comment]
it didn't solve itself, was fixed by https://github.com/OCA/server-tools/blob/8.0/database_cleanup/model/purge_modules.py#L35 - seems it was just forgotten to close this issue
