### ISSUE TITLE
KeyError: 'message_unread' when sending mail in fetchmail_notify_error_to_sender

### ISSUE THREAD

**Issue by TTPBruce** [OCA/server-tools#1652]
Running on Odoo 12 Enterprise
```
Traceback (most recent call last):
  File "/opt/odoo/addons/fetchmail/models/fetchmail.py", line 178, in fetch_mail
    res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 1421, in message_process
    routes = self.message_route(msg_txt, msg, model, thread_id, custom_values)
  File "/opt/odoo/tt_power_group/fetchmail_notify_error_to_sender/models/mail_thread.py", line 30, in message_route
    fetchmail_server.id)
  File "/opt/odoo/addons/mail/models/mail_template.py", line 541, in send_mail
    mail = Mail.create(values)
  File "<decorator-gen-131>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/addons/fetchmail/models/mail_mail.py", line 18, in create
    return super(MailMail, self).create(values)
  File "<decorator-gen-118>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/addons/mail/models/mail_mail.py", line 68, in create
    new_mail = super(MailMail, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/models.py", line 3537, in create
    for data in parent_data_list
  File "<decorator-gen-116>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/addons/mail/models/mail_message.py", line 994, in create
    message._invalidate_documents()
  File "/opt/odoo/addons/mail/models/mail_message.py", line 937, in _invalidate_documents
    ], ids=[record.res_id])
  File "/opt/odoo/odoo/models.py", line 5157, in invalidate_cache
    fields = [self._fields[n] for n in fnames]
  File "/opt/odoo/odoo/models.py", line 5157, in <listcomp>
    fields = [self._fields[n] for n in fnames]
KeyError: 'message_unread'
```

**Comment by HviorForgeFlow** [comment]
Hi @TTPBruce, It is not related with EE. I think we fixed this same problem in another module during migrations to v12. We'll fix it ASAP.

@mreficent Do you remember this error? Did you do a fix in odoo itself, or just a hack on that module?

**Comment by TTPBruce** [comment]
Thanks for the quick response. Please let me know if there is anything I can do to help/reproduce this issue.

**Comment by HviorForgeFlow** [comment]
@TTPBruce Have you this commit on your Odoo 12 code??
https://github.com/odoo/odoo/commit/fa294d2059bac600402363d5791a48de64316c2e

@mreficent do the fix there. https://github.com/odoo/odoo/pull/31799

**Comment by TTPBruce** [comment]
That commit fixed it - thanks.

**Comment by HviorForgeFlow** [comment]
Close it then :smile:

**Comment by TTPBruce** [comment]
Oops closed :D
