### ISSUE TITLE
[10.0] onchange_helper: SQL error happens from _get_message_needaction method 

### ISSUE THREAD

**Issue by metaminux** [OCA/server-tools#1693]
I think this issue is related to #1510 changes.

I'm using [account_invoice_inter_company module](https://github.com/OCA/multi-company/tree/10.0/account_invoice_inter_company) for a while but I can't validate an inter-company invoice as of September 18th.

This is the trace returned by Odoo :
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/external-addons/oca-multi-company/account_invoice_inter_company/models/account_invoice.py", line 46, in action_invoice_open
    dest_journal_type)
  File "/mnt/external-addons/oca-multi-company/purchase_sale_inter_company/models/account_invoice.py", line 13, in _inter_company_create_invoice
    dest_company, dest_inv_type, dest_journal_type)
  File "/mnt/external-addons/oca-multi-company/account_invoice_inter_company/models/account_invoice.py", line 103, in _inter_company_create_invoice
    dest_inv_type, dest_journal_type, dest_company)
  File "/mnt/external-addons/oca-multi-company/account_invoice_inter_company/models/account_invoice.py", line 175, in _prepare_invoice_data
    dest_partner_data, ['partner_id'])
  File "/mnt/external-addons/oca-server-tools/onchange_helper/models/models.py", line 196, in play_onchanges
    dirties = self._compute_onchange_dirty(origin, record, name)
  File "/mnt/external-addons/oca-server-tools/onchange_helper/models/models.py", line 43, in _compute_onchange_dirty
    new_value = modified_record[field_name]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5269, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 929, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1052, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 984, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 197, in _get_message_needaction
    (self.env.user.partner_id.id, self._name, tuple(self.ids),))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 4: ...    WHERE msg.model = 'account.invoice' AND msg.res_id in ()
                                                                      ^
```
The "play_onchanges" method is called for field "partner_id" on a new invoice (I mean "newId" one) and error is encountered when computing the "message_needaction" field.

Not sure about what to do, but I suppose this could affect all models inheriting "mail.thread"...

I can provide more information if needed.

**Comment by lmignon** [comment]
@metaminux Thank you for the report. This error comes from an issue fixed into odoo... https://github.com/odoo/odoo/commit/52526920085e94727ddc12d188af826ede7fd6d9 This error should disappear if you upgrade Odoo.

**Comment by metaminux** [comment]
@lmignon You're right, I'm using the docker image for Odoo 10.0 which is using the nightly deb package with ODOO_RELEASE = 20190816, but you commited the fix in the 10.0 branch on september the 13th, right ?
So this error will occur until odoo/docker is updated...

**Comment by lmignon** [comment]
right...

**Comment by metaminux** [comment]
For those using docker image, as Odoo 10.0 image is now frozen, you could use a custom Dockerfile beginning with :
```Dockerfile
FROM odoo:10.0

USER root

ARG ODOO_RELEASE=20191007
ARG ODOO_SHA=0293db656a34d047695a2cd4a9b5d9ed6126846c
RUN set -x; \
        curl -o odoo.deb -sSL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
        && echo "${ODOO_SHA} odoo.deb" | sha1sum -c - \
        && dpkg --force-depends -i odoo.deb \
        && apt-get update \
        && apt-get -y install -f --no-install-recommends git python-xlrd \
        && rm -rf /var/lib/apt/lists/* odoo.deb
```
