### ISSUE TITLE
languages eror

### ISSUE THREAD

**Issue by omer633** [OCA/server-tools#1741]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 970, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).last_activity_time', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 970, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.employee(1,).last_activity_time', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\res_users.py", line 1294, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\res_users.py", line 454, in read
    return super(Users, self).read(fields=fields, load=load)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 2901, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 5579, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 994, in __get__
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1075, in compute_value
    records._compute_field_value(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3897, in _compute_field_value
    field.compute(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 566, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 5579, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 994, in __get__
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1075, in compute_value
    records._compute_field_value(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3895, in _compute_field_value
    getattr(self, field.compute)()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\hr\models\hr_employee_base.py", line 73, in _compute_last_activity
    employee.last_activity_time = format_time(self.env, last_activity_datetime, time_format='short')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\misc.py", line 1318, in format_time
    locale = babel.Locale.parse(lang.code)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\babel\core.py", line 333, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'deutsch'

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
