### ISSUE TITLE
[10.0] letsencrypt cURL returns a 404, but I can access URL through navigator

### ISSUE THREAD

**Issue by nfortea** [OCA/server-tools#1767]
I recently install letsencrypt. When I tried to execute Update letsencrypt certificates for first time to obtain .crt file I received next error:

2020-02-17 13:08:44,185 20948 INFO ? werkzeug: 127.0.0.1 - - [17/Feb/2020 13:08:44] "GET /.well-known/acme-challenge/6DtF_0imQe9s-leL3oSwcHBMvBdxM8BNBLKGcI7KrGY HTTP/1.0" 404 -
2020-02-17 13:08:44,187 20948 ERROR oxortical_PRODUCCION_2020 odoo.addons.base.ir.ir_cron: Call of self.env[u'letsencrypt'].cron(*()) failed in Job #6
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_cron.py", line 126, in _callback
    getattr(model, method_name)(*args)
  File "/opt/odoo/extra-addons/server-tools/letsencrypt/models/letsencrypt.py", line 148, in cron
    account_key, csr, acme_challenge, log=_logger, CA=DEFAULT_CA)
  File "/usr/local/lib/python2.7/dist-packages/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /var/lib/odoo/.local/share/Odoo/letsencrypt/acme-challenge/6DtF_0imQe9s-leL3oSwcHBMvBdxM8BNBLKGcI7KrGY, but couldn't download http://oficina.domain.tld/.well-known/acme-challenge/6DtF_0imQe9s-leL3oSwcHBMvBdxM8BNBLKGcI7KrGY: Error:
Url: http://oficina.domain.tld/.well-known/acme-challenge/6DtF_0imQe9s-leL3oSwcHBMvBdxM8BNBLKGcI7KrGY
Data: None
Response Code: 404
Response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

But I can access to http://oficina.domain.tld/.well-known/acme-challenge/6DtF_0imQe9s-leL3oSwcHBMvBdxM8BNBLKGcI7KrGY through a navigator I obtain a 200 state.
I obtain a 404 state to favicon too.

**Comment by nfortea** [comment]
Any idea?
