### ISSUE TITLE
Error Uninstalling Auditlog Odoo 12 Community

### ISSUE THREAD

**Issue by FelipeSotoHerrera** [OCA/server-tools#1879]
Hello everyone, here is the error that occurs when you uninstall this module, which I find excellent. Unfortunately, it leaves this detail of not being able to access the modules associated with the models that were created in the registration rules at the time.

Odoo Server Error
Traceback (most recent call last):
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7fc9103d70d0>, frozenset({1, 2, 3, 6, 7, 8, 18, 19, 20, 21, 22, 23, 26, 30, 36, 39, 40, 41, 49, 50, 51, 52}), 'hr.employee')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 376

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(376,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/models.py", line 1468, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-36>", line 2, in get_bindings
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/base/models/ir_actions.py", line 122, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/base/models/ir_actions.py", line 210, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/models.py", line 2797, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/models.py", line 5123, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/addons/base/models/ir_actions.py", line 170, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/api.py", line 821, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/media/felipe/Respaldo/Proyecto/Odoo/Proyectos/odoo-12.0.post20190928/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'auditlog.log'

At this moment I am adding this small problem when uninstalling, I still cannot find what causes it as such, so while I continue searching for a solution, I leave you notified for your knowledge.

**Comment by enedinovillaverde** [comment]
I don't know if you have solved your problem...but here you have the answer for V13.

https://github.com/OCA/server-tools/issues/1977
