### ISSUE TITLE
auditlog: unicode error when trying to log changes to MuK DMS file

### ISSUE THREAD

**Issue by olaf-wagner** [OCA/server-tools#1968]
After activating the auditlog for MuK DMS file objects I get exceptions when trying to upload a binary file:
<pre>
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/lib/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/lib/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 757, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 737, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-471>", line 2, in create_fast
  File "/opt/odoo/lib/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/lib/addons/oca-mirror-server-tools/auditlog/models/rule.py", line 240, in create_fast
    new_records = create_fast.origin(self, vals_list, **kwargs)
  File "<decorator-gen-384>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/lib/addons/muk-dms/muk_dms_mail/models/file.py", line 46, in create
    return super(File, self.with_context(mail_create_nolog=True)).create(vals_list)
  File "<decorator-gen-132>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/lib/odoo/addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-368>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/lib/addons/muk-dms/muk_dms_thumbnails/models/file.py", line 144, in create
    res =  super(File, self).create(vals_list)
  File "<decorator-gen-353>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/lib/addons/muk-dms/muk_dms/models/mixins_thumbnail.py", line 148, in create
    return super(Thumbnail, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 3870, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 1169, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/lib/addons/muk-dms/muk_dms_lobject/models/file.py", line 100, in _inverse_content
    super(File, self - records)._inverse_content()
  File "/opt/odoo/lib/addons/muk-dms/muk_dms_file/models/file.py", line 104, in _inverse_content
    self.browse(ids).write(dict(vals))
  File "/opt/odoo/lib/addons/oca-mirror-server-tools/auditlog/models/rule.py", line 317, in write_fast
    'write', old_values, new_values, {'log_type': log_type})
  File "/opt/odoo/lib/addons/oca-mirror-server-tools/auditlog/models/rule.py", line 391, in create_logs
    log, diff.changed(), old_values, new_values)
  File "/opt/odoo/lib/addons/oca-mirror-server-tools/auditlog/models/rule.py", line 458, in _create_log_line_on_write
    log_line_model.create(log_vals)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/lib/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/lib/odoo/odoo/models.py", line 3834, in create
    records = self._create(data_list)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 3921, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 846, in convert_to_column
    return pycompat.to_native(value)
  File "/opt/odoo/lib/odoo/odoo/tools/pycompat.py", line 68, in to_native
    return source.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
</pre>
The problem seems to occur when logging the `content_file` field of muk_dms_file. At least it can be avoided by adding that field to the internal `FIELDS_BLACKLIST` in rule.py. I don't think that is a proper solution though.

**Comment by pedrobaeza** [comment]
Then the problem is on the other module, not here.
