### ISSUE TITLE
Issue After uninstalling auditlog odoo 13

### ISSUE THREAD

**Issue by Dhananjayagarwal** [OCA/server-tools#1977]
After uninstalling Auditlog module it doesn't allow to use related modules i.e For which rules were created. Any fix on this would be appreciated.

Here is log trail using with odoo version 13

Traceback (most recent call last):
  File "/odoo13_ent/odoo13_ent-server/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/odoo13_ent/odoo13_ent-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7eff8fb49ca0>, frozenset({1, 2, 3, 6, 7, 14, 17, 19, 20, 21, 22, 23, 25, 26, 31, 37, 38, 46, 47, 52, 53, 68, 69, 71}), 'sale.order')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo13_ent/odoo13_ent-server/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 680

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo13_ent/odoo13_ent-server/odoo/fields.py", line 1000, in __get__
    value = env.cache.get(record, self)
  File "/odoo13_ent/odoo13_ent-server/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(680,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo13_ent/odoo13_ent-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo13_ent/odoo13_ent-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo13_ent/odoo13_ent-server/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo13_ent/odoo13_ent-server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 1463, in load_views
    result['fields_views'] = {
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 1464, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
  File "/odoo13_ent/odoo13_ent-server/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo13_ent/odoo13_ent-server/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 1560, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-34>", line 2, in get_bindings
  File "/odoo13_ent/odoo13_ent-server/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo13_ent/odoo13_ent-server/odoo/addons/base/models/ir_actions.py", line 123, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/odoo13_ent/odoo13_ent-server/odoo/addons/base/models/ir_actions.py", line 204, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 2945, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 5689, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo13_ent/odoo13_ent-server/odoo/fields.py", line 1024, in __get__
    self.compute_value(recs)
  File "/odoo13_ent/odoo13_ent-server/odoo/fields.py", line 1109, in compute_value
    records._compute_field_value(self)
  File "/odoo13_ent/odoo13_ent-server/odoo/models.py", line 3966, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo13_ent/odoo13_ent-server/odoo/addons/base/models/ir_actions.py", line 171, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/odoo13_ent/odoo13_ent-server/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/odoo13_ent/odoo13_ent-server/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'auditlog.log'

Any fix for this would be appreciated

**Comment by Dhananjayagarwal** [comment]
Root Cause for this error is.

After uninstalling its not deleting related records from ir.actions.actions. i.e since after subscribing in rules it adds quick link to view logs from each record.

so after uninstalling those records needs to be deleted as well from ir.actions.actions.
@sebalix Can you please help

**Comment by Dhananjayagarwal** [comment]
I Was able to fix the issue by adding by uninstallhook and remove **audit log** action menu from **ir_actions**. 
It would be great if we could add to the repository. 
@OCA-git-bot 

Thanks

**Comment by sergioeix** [comment]
same issue here @Dhananjayagarwal can you share your fix or make a PR, if anyone reaches this post, it can be fixed manually deleting the action from setting->technical->actions
Ty
