### ISSUE TITLE
[14.0] Auditlog not able to open logs

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-tools#2086]
Runbot:
http://3482927-14-0-1dc072.runbot2.odoo-community.org/web?debug=1#action=105&active_id=6&model=auditlog.log&view_type=list&cids=1&menu_id=4

Video:
https://drive.google.com/file/d/1_v98Knn28KaHL92S10xnlInKLv5y5CF7/view

Traceback:
```
Error:
Traceback:
TypeError: Cannot read property 'colspan' of undefined
    at http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2255:34
    at Array.forEach (<anonymous>)
    at Class._renderInnerGroup (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2254:75)
    at Class._renderTagGroup (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2270:248)
    at Class._renderNode (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2262:244)
    at http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2267:17
    at Function._.map._.collect (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/205-fb17376/web.assets_common.js:109:270)
    at Class._renderOuterGroup (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2266:18)
    at Class._renderTagGroup (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2271:13)
    at Class._renderNode (http://3482927-14-0-1dc072.runbot2.odoo-community.org/web/content/206-f8de16a/web.assets_backend.js:2262:244)
```

@StefanRijnhart

**Comment by StefanRijnhart** [comment]
Blimey! How did that happen? Should be fixed with https://github.com/OCA/server-tools/pull/2087. Thanks for noting!

**Comment by CasVissers-360ERP** [comment]
Thnx!
