### ISSUE TITLE
[14.0] module_change_auto_install, cannot create new database enabling auto_install

### ISSUE THREAD

**Issue by GSLabIt** [OCA/server-tools#2242]
## Module
module_change_auto_install

## Describe the bug
Setting `website_odoo_debranding` auto installable in config file, will raise issue on database creation

## To Reproduce
**Affected versions**: 14.0

1. add `modules_auto_install_enabled = website_odoo_debranding` in odoo config
2. go to `https://domain/web/database/manager` and create a new database
3. Error is raised:
```
2021-12-22 14:04:21,051 4045732 INFO None odoo.service.db: Create database `test3`.
2021-12-22 14:04:24,824 4045732 INFO None odoo.addons.module_change_auto_install.patch: Module 'website_odoo_debranding' has been marked as auto installable.
2021-12-22 14:04:24,850 4045732 ERROR None odoo.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 59, in _initialize_db
    odoo.modules.db.initialize(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/db.py", line 73, in initialize
    (id, d, d in (info['auto_install'] or ()))
TypeError: argument of type 'bool' is not iterable
2021-12-22 14:04:24,871 4045732 ERROR None odoo.modules.loading: Database test3 not initialized, you can force it with `-i base`
2021-12-22 14:04:24,930 4045732 INFO test3 odoo.sql_db: ConnectionPool(used=0/count=1/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=test3 port=5432 sslmode=prefer'
2021-12-22 14:04:24,935 4045732 INFO test3 werkzeug: 127.0.0.1 - - [22/Dec/2021 14:04:24] "POST /web/database/create HTTP/1.1" 200 - 2827 1.488 2.618
2021-12-22 14:04:43,795 4045737 ERROR test3 odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^

2021-12-22 14:04:43,796 4045737 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database test3.
2021-12-22 14:04:43,796 4045737 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=test3 port=5432 sslmode=prefer'
2021-12-22 14:04:43,816 4045737 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=test port=5432 sslmode=prefer'
2021-12-22 14:04:44,790 4045738 ERROR test3 odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^

2021-12-22 14:04:44,791 4045738 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database test3.
2021-12-22 14:04:44,791 4045738 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=test3 port=5432 sslmode=prefer'
2021-12-22 14:04:44,818 4045738 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=test port=5432 sslmode=prefer'
```

**Expected behavior**
Error should not be raised and database will be created properly

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by GSLabIt** [comment]
@legalsylvain, any hint on how to fix?
