### ISSUE TITLE
odoo 14 base_name_search_improved not working at all

### ISSUE THREAD

**Issue by alielnagar** [OCA/server-tools#2255]
odoo 14 base_name_search_improved not working at all
today oddo 14  bulid

**Comment by Rad0van** [comment]
See #2271 for fix...

**Comment by alahlou-com** [comment]
Hello,
Still can't install this module on odoo 14, i have the following error:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 404, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 391, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 454, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 570, in _button_immediate_function
    self._cr.commit()
  File "<decorator-gen-9>", line 2, in commit
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 451, in commit
    flush_env(self)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 78, in flush_env
    env_to_flush['base'].flush()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5486, in flush
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5945, in recompute
    process(field)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5929, in process
    field.recompute(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1176, in recompute
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1185, in compute_value
    fields = records.pool.field_computed[self]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: ir.module.module.views_by_module
