### ISSUE TITLE
Supacalendar ist not able to handle recurrency meetings

### ISSUE THREAD

**Issue by mh-manatec** [OCA/server-tools#235]
When i track calendar.event and configure recurrent meeting the server says:

Traceback (most recent call last):
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo8/opt/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo8/opt/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo8/opt/server-tools/super_calendar/models/super_calendar_configurator.py", line 75, in generate_calendar_records
    configurator._generate_record_from_line(line)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8/opt/server-tools/super_calendar/models/super_calendar_configurator.py", line 89, in _generate_record_from_line
    super_calendar_pool.create(values[record])
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 4076, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 4196, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 2256, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/odoo/odoo8/local/lib/python2.7/site-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 1426, in convert_to_cache
    return record.env[res_model].browse(int(res_id))
ValueError: invalid literal for int() with base 10: '14-20151110120000'

**Comment by danimaribeiro** [comment]
I confirm the issue:

The id of 'calendar.event' is a string like '14-20151110120000' when the event is recurrent, I don't know yet why Odoo changes a integer field to string in this case.

cur_rec['id'] returns a string
https://github.com/OCA/server-tools/blob/8.0/super_calendar/models/super_calendar_configurator.py#L172

**Comment by danimaribeiro** [comment]
Fixed here:
https://github.com/OCA/server-tools/pull/392

**Comment by pedrobaeza** [comment]
Closing then
