### ISSUE TITLE
It is not possible run database analyse between odoo v.12 and odoo v.15

### ISSUE THREAD

**Issue by zurawmaco** [OCA/server-tools#2389]
## Module
[upgrade_analysis](https://github.com/OCA/server-tools/tree/14.0/upgrade_analysis)

## Describe the bug
I am trying to run my own database analysis according to the [documentation](https://oca.github.io/OpenUpgrade/analyse.html) between modules in odoo v.12 and odoo v.15. When I started _New Analysis_ I got following error message:

>Traceback (most recent call last):
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/addons/web/controllers/main.py", line 1351, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/server-tools/upgrade_analysis/models/upgrade_analysis.py", line 154, in analyze
    remote_xml_records = [
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/server-tools/upgrade_analysis/models/upgrade_analysis.py", line 155, in <listcomp>
    {field: record[field] for field in flds}
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/server-tools/upgrade_analysis/models/upgrade_analysis.py", line 155, in <dictcomp>
    {field: record[field] for field in flds}
Exception

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/marcin/Documents/Macopedia/PanelMaco/analyse_more_versions/odoo15/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'definition'

## To Reproduce

1. Set up two servers of subsequent Odoo releases
2. On both instances start the Generate Records Wizard.
3. On the target instance (this is the more recent version): from the analysis menu, select the Comparison Configuration option and create a new config to connect to the other instance.
4. Start New Analysis ===>>> ERROR

**Expected behavior**
Analysis files are created

**Additional context**
In documentation I read that: 
> You can create analysis files on any set of modules between any two versions of Odoo. 

Commit adding field _definition_ was created in 2021. Is it possible to run analyse now between any versions of Odoo? 

Best Regards

**Comment by pedrobaeza** [comment]
That's not possible. This is prepared to run between one version and the previous one. If you want that (which is not advisable, you must adapt the 12.0 version of the `openupgrade_records` module to allow it.

**Comment by zurawmaco** [comment]
I thought it could be great to make such an analyse for custom modules, then write a migration script for them and then upgrade database. It's a pitty that I cannot do it like that

So I need to write custom module for odoo v.13, then for odoo v.14 and then finally I can use custom module for odoo v.15.

**Comment by pedrobaeza** [comment]
Not really. Just see the migration diff of your module and deduce the needed migration scripts. They will likely be very few.

**Comment by legalsylvain** [comment]
It has been discussed here : https://github.com/OCA/OpenUpgrade/pull/2956

You can try the patch I propose for jour custom analysis. Maybe it will work. Kind regards.
