### ISSUE TITLE
[15.0] auditlog: breaks partner_firstname tests

### ISSUE THREAD

**Issue by amh-mw** [OCA/server-tools#2487]
## Module
auditlog

## Describe the bug
If both auditlog and partner_firstname module are installed, tests fail.

## To Reproduce
15.0

1. Base `odoo:15` docker image, with extra mount /mnt/oca-addons
1. `odoo --addons-path=/mnt/oca-addons/partner-contact,/mnt/oca-addons/server-tools  --init=auditlog,partner_firstname --test-enable`

Sample failures:
```
2022-12-02 17:48:07,295 1 ERROR odoo odoo.addons.partner_firstname.tests.test_copy: FAIL: UserCase.test_copy_firstname_lastname
Traceback (most recent call last):
  File "/mnt/oca-addons/partner-contact/partner_firstname/tests/test_copy.py", line 41, in test_copy_firstname_lastname
    self.compare(copy)
  File "/mnt/oca-addons/partner-contact/partner_firstname/tests/test_copy.py", line 31, in compare
    self.assertEqual(copy.name, "Firstname2 Lastname2")
AssertionError: 'Firstname Lastname (copy)' != 'Firstname2 Lastname2'
- Firstname Lastname (copy)
?                   ^^^^^^^
+ Firstname2 Lastname2
?          +         ^
```
```
2022-12-02 17:48:07,578 1 ERROR odoo odoo.addons.partner_firstname.tests.test_delete: ERROR: PersonCase.test_computing_after_unlink
Traceback (most recent call last):
  File "/mnt/oca-addons/partner-contact/partner_firstname/tests/test_delete.py", line 22, in test_computing_after_unlink
    record = self.env[self.model].with_context(**self.context).create(data)
  File "<decorator-gen-98>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_partner.py", line 619, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4070, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4235, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/mnt/oca-addons/partner-contact/partner_firstname/models/res_partner.py", line 203, in _check_name
    raise exceptions.EmptyNamesError(record)
odoo.addons.partner_firstname.exceptions.EmptyNamesError: ("Error(s) with partner 536's name.", 'No name is set.')
```

**Expected behavior**
Tests pass.

**Additional context**
```
% git submodule
 3887ea9438e677925a4e32b292f2f97387105565 oca/partner-contact (heads/15.0)
 0a3dda46e1938059308e8a2a9a9e03a1df566055 oca/server-tools (heads/15.0)
```

**Comment by amh-mw** [comment]
Through process of elimination, I've narrowed this down to the AuditLogRuleTestForUserFields test class in oca/server-tools/auditlog/tests/test_auditlog.py. It appears that patched model methods are not being reverted, even though self.auditlog_rule is being unlinked (and unsubscribed) in the last test.

**Comment by francesco-ooops** [comment]
@amh-mw thank you for your investigation! do you know if the issue is present also in v14 and v16?

**Comment by amh-mw** [comment]
I only have v15 customers, so I haven't checked. My steps to reproduce should work equally well against an `odoo:14` or `odoo:16` container, so it should be straightforward to determine.

**Comment by amh-mw** [comment]
A quick glance at `git diff upstream/14.0 upstream/15.0 -- auditlog` shows some sort of refactoring of the tests, so the bug could have been introduced in 15.0

A quick glance at `git diff upstream/15.0 upstream/16.0 -- auditlog` looks like mostly migration related tweaks, so the bug is almost certainly in 16.0
