### ISSUE TITLE
Cannot delete Auditlog Rules

### ISSUE THREAD

**Issue by BT-shautz** [OCA/server-tools#2506]
## Module
Auditlog

## Describe the bug
An error is triggered when trying to delete an Auditlog Rule, this error isn't always triggered and is quite inconsistent.
The suspected cause is the deletion of the attrs added in the "_patch_methods" call, like "auditlog_ruled_create", that is done in the "_revert_methods" call with:
- delattr(type(model_model), "auditlog_ruled_%s" % method)

And resulting in the following error message:
```
Traceback (most recent call last):
  File "/home/odoo/repos/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/repos/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: auditlog_ruled_unlink
```

## To Reproduce
**Affected versions**: We could reproduce this on Odoo v14 and v15, other versions might be affected as well.

1. Create an Audit Rule
2. Attempt to delete it.
3. Sometimes the above mentioned error is triggered.

**Expected behavior**
The Rule is deleted with no errors (the added attributes are removed accordingly).

**Comment by BT-shautz** [comment]
Further info regarding this issue:
The new attributes were created through sudo(), if the delattr() is called with self.sudo() as well the deletion doesn't trigger an error anymore.
