### ISSUE TITLE
[V8] Database cleanup module error

### ISSUE THREAD

**Issue by sharkutz** [OCA/server-tools#259]
When pressing Purge absolute modules, nothing is displayed and the following error is shown:

Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 1259, in run
    [action_id], request.context)
  File "/opt/odoo/odooV8/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_actions.py", line 1002, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_actions.py", line 836, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odooV8/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4064, in create
    vals = self._add_missing_default_values(vals)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 472, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 1802, in _add_missing_default_values
    defaults = self.default_get(cr, uid, list(missing_defaults), context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/database_cleanup/model/purge_modules.py", line 102, in default_get
    cr, uid, fields, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/database_cleanup/model/purge_wizard.py", line 49, in default_get
    res['purge_line_ids'] = self.find(cr, uid, context=None)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/database_cleanup/model/purge_modules.py", line 115, in find
    module_pool.unlink(cr, uid, module.id, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/module/module.py", line 349, in unlink
    return super(module, self).unlink(cr, uid, ids, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3622, in unlink
    'where id IN %s', (sub_ids,))
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "module" violates not-null constraint
DETAIL:  Failing row contains (948, 2015-09-08 12:49:00.084316, 2015-09-08 12:49:00.084316, null, 153, product_public_category_product_template_rel, null, null, null, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."ir_model_relation" SET "module" = NULL WHERE $1 OPERATOR(pg_catalog.=) "module""
" while evaluating
u"wizard_id = self.create(cr, uid, {}, context=context)\naction = {\n    'type': 'ir.actions.act_window',\n    'views': [(False, 'form')],\n    'res_model': 'cleanup.purge.wizard.module',\n    'res_id': wizard_id,\n    'flags': {\n        'action_buttons': False,\n        'sidebar': False,\n    },\n}"

**Comment by gurneyalex** [comment]
@sharkutz  @hbrunn do you know if this is still relevant?

**Comment by pedrobaeza** [comment]
I don't think so, so I close.
