### ISSUE TITLE
Error, when human resources manager edit employer

### ISSUE THREAD

**Issue by Endika** [OCA/server-tools#268]
module: auditlog
version: 8.0

**Steps to reproduce**
- Created new rule: for hr.employee models and checked write, unlink and create.
- Administrator user subscribe in this rules.
- Other user with Manager in human resources update any employeer and save. And show the error.

**Current behavior**

This is log:

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  **File "/opt/odoo/oca/auditlog/models/rule.py", line 275, in write
    (d['id'], d) for d in self.sudo().read(list(self._fields)))**
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3178, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3373, in _read_from_database
    record._cache.update(record._convert_to_cache(vals, validate=False))
  File "/opt/odoo/odoo/openerp/models.py", line 5343, in _convert_to_cache
    for name, value in values.iteritems()
  File "/opt/odoo/odoo/openerp/models.py", line 5344, in <dictcomp>
    if name in fields
  File "/opt/odoo/odoo/openerp/fields.py", line 1086, in convert_to_cache
    value = float(value or 0.0)
**TypeError: float() argument must be a string or a number**

**Expected behavior**
- The human resources Manager can edit the employeers

**Comment by Endika** [comment]
Try to install
auditlog and hr_payroll
 and create new rule from hr.employee and subscribe.
And other user (Human resources manager) edit any employer profile.

Auditlog is incompatible with hr_payroll

**Comment by StefanRijnhart** [comment]
Bug seems to be in Odoo and fixed already. See my comments on the PR.

**Comment by Endika** [comment]
SOLVED https://github.com/OCA/server-tools/pull/269
