### ISSUE TITLE
upgrade_analysis: Odoo-version

### ISSUE THREAD

**Issue by BartvandenHout** [OCA/server-tools#2736]
## Module
upgrade_analysis

## Describe the bug
Retrieved Odoo-version 

## To Reproduce
14.0, 15.0, probably others

1. Perform Analysis

**Expected behavior**
Work out the correct main version 14.0 even though the retrieved version is formatted as 14.0-20230920

**Additional context**
models/upgrade_analysis.py

Current code, line 78:
            if float(self.config_id.version < 14.0:
                return connection.env["openupgrade.record"]
            else:
                return connection.env["upgrade.record"]

Proposed code:
            try:
                version, subversion = self.config_id.version.split("-")
            except ValueError:
                version = self.config_id.version
            if float(version) < 14.0:
                return connection.env["openupgrade.record"]
            else:
                return connection.env["upgrade.record"]

**Comment by legalsylvain** [comment]
could you make a PR ? it will be more readable.

thanks !

**Comment by pedrobaeza** [comment]
But it should work as is AFAIK.

**Comment by BartvandenHout** [comment]
FYI: using Python 3.9.2 I get this error with current code:

2023-10-16 14:04:37,554 417033 ERROR odoodev3 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1328, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons_oe/upgrade_analysis/models/upgrade_analysis.py", line 130, in analyze
    RemoteRecord = self._get_remote_model(connection, "record")
  File "/usr/lib/python3/dist-packages/odoo/addons_oe/upgrade_analysis/models/upgrade_analysis.py", line 78, in _get_remote_model
    if float(self.config_id.version) < 14.0:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: could not convert string to float: '14.0-20230920'

**Comment by pedrobaeza** [comment]
OK, true. String comparison should be done instead of converting to float.

**Comment by BartvandenHout** [comment]
We'll be setting up a specific development-server for OCA-modules in a couple of weeks. That way I can work (cleanly) on OCA addons using github. But for now this is the only way I can help. Sorry about that.
