### ISSUE TITLE
[16.0] Tests failing: cron_daylight_saving_time_resistant

### ISSUE THREAD

**Issue by CRogos** [OCA/server-tools#2898]
## Module
cron_daylight_saving_time_resistant

## Describe the bug
All PR on v16.0 run into this Test workflow error. Does anyone know what could be the cause and how to fix it?
![image](https://github.com/OCA/server-tools/assets/1799080/7ea05773-c2d0-4a4e-b1ba-e364bb3193e4)

## To Reproduce
**Affected versions**: 16.0

Execute Tests workflow ends in an error.

**Additional context**
https://github.com/OCA/server-tools/actions/runs/8553012765

```
2021-10-30 15:00:10,000 391 ERROR odoo odoo.addons.base.models.ir_cron: Call from cron {'en_US': 'TestCron'} for server action #424 failed in Job #24 
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_cron.py", line 390, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 651, in run
    self.env[action.model_name].check_access_rights("write")
  File "/opt/odoo/odoo/api.py", line 550, in __getitem__
    return self.registry[model_name](self, (), ())
  File "/opt/odoo/odoo/modules/registry.py", line 190, in __getitem__
    return self.models[model_name]
KeyError: False
2021-10-30 15:00:10,000 391 ERROR odoo odoo.sql_db: bad query: RELEASE SAVEPOINT "13b0b903-3992-11ec-8455-97d00d0ab478"
ERROR: savepoint "13b0b903-3992-11ec-8455-97d00d0ab478" does not exist
 
2021-10-30 15:00:10,000 391 ERROR odoo odoo.sql_db: bad query: ROLLBACK TO SAVEPOINT "13b0b903-3992-11ec-8455-97d00d0ab478"
ERROR: savepoint "13b0b903-3992-11ec-8455-97d00d0ab478" does not exist
 
2021-10-30 15:00:10,000 391 WARNING odoo odoo.sql_db: Found different un-closed cursor when trying to close <odoo.sql_db.TestCursor object at 0x7f7e1f9e90f0>: <odoo.sql_db.TestCursor object at 0x7f7e196936a0> 
2024-04-04 10:23:26,468 391 INFO odoo odoo.addons.cron_daylight_saving_time_resistant.tests.test_dst: ====================================================================== 
2024-04-04 10:23:26,468 391 ERROR odoo odoo.addons.cron_daylight_saving_time_resistant.tests.test_dst: ERROR: TestDST.test_cron
Traceback (most recent call last):
  File "/opt/odoo/odoo/sql_db.py", line 176, in __exit__
    self.commit()
  File "/opt/odoo/odoo/sql_db.py", line 558, in commit
    self._savepoint.close(rollback=False)
  File "/opt/odoo/odoo/sql_db.py", line 86, in close
    self._close(rollback)
  File "/opt/odoo/odoo/sql_db.py", line 94, in _close
    self._cr.execute(SQL('RELEASE SAVEPOINT {}').format(self._name))
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidSavepointSpecification: savepoint "13b0b903-3992-11ec-8455-97d00d0ab478" does not exist


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/module-oca-server-tools/module-oca-server-tools/cron_daylight_saving_time_resistant/tests/test_dst.py", line 71, in test_cron
    self._check_cron_date_after_run(cron, "2021-10-30 15:00:00")
  File "/__w/module-oca-server-tools/module-oca-server-tools/cron_daylight_saving_time_resistant/tests/test_dst.py", line 43, in _check_cron_date_after_run
    registry["ir.cron"]._process_job(db, new_cr, job)
  File "/__w/module-oca-server-tools/module-oca-server-tools/cron_daylight_saving_time_resistant/models/ir_cron.py", line 48, in _process_job
    with cls.pool.cursor() as job_cr:
  File "/opt/odoo/odoo/sql_db.py", line 178, in __exit__
    self.close()
  File "/opt/odoo/odoo/sql_db.py", line 540, in close
    self.rollback()
  File "/opt/odoo/odoo/sql_db.py", line 571, in rollback
    self._savepoint.rollback()
  File "/opt/odoo/odoo/sql_db.py", line 89, in rollback
    self._cr.execute(SQL('ROLLBACK TO SAVEPOINT {}').format(self._name))
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidSavepointSpecification: savepoint "13b0b903-[399](https://github.com/c4a8-odoo/module-oca-server-tools/actions/runs/8553054039/job/23435432810?pr=1#step:8:400)2-11ec-8455-97d00d0ab478" does not exist

```

**Comment by CRogos** [comment]
fixed by https://github.com/OCA/server-tools/pull/2899
