### ISSUE TITLE
[15] session_db module not loading

### ISSUE THREAD

**Issue by b-milescu** [OCA/server-tools#3013]
## Module
session_db

## Describe the bug
Module is not loading throwing the error:
```
debian-12-odoo-1        | Traceback (most recent call last):
debian-12-odoo-1        |   File "/opt/bitnami/odoo/lib/odoo-15.0.post20240710-py3.10.egg/odoo/service/server.py", line 1210, in load_server_wide_modules
debian-12-odoo-1        |     odoo.modules.module.load_openerp_module(m)
debian-12-odoo-1        |   File "/opt/bitnami/odoo/lib/odoo-15.0.post20240710-py3.10.egg/odoo/modules/module.py", line 407, in load_openerp_module
debian-12-odoo-1        |     __import__('odoo.addons.' + module_name)
debian-12-odoo-1        |   File "/bitnami/odoo/addons/session_db/__init__.py", line 1, in <module>
debian-12-odoo-1        |     from . import pg_session_store
debian-12-odoo-1        |   File "/bitnami/odoo/addons/session_db/pg_session_store.py", line 12, in <module>
debian-12-odoo-1        |     import werkzeug.contrib.sessions
debian-12-odoo-1        | ModuleNotFoundError: No module named 'werkzeug.contrib'
```

## To Reproduce
**Affected versions**: 15

1. Use bitnami Odoo container v15 located [here] (https://github.com/bitnami/containers/tree/main/bitnami/odoo)
2. Mount the module into the addons folder
3. docker-compose up

**Expected behavior**
Module should load successfully 

**Additional context**
OS: Debian 12
Python: 3.10

**Comment by gdgellatly** [comment]
You will probably need to backport the v16 changes, although you might get away with just using the vendor import and adjusting accordingly. But definitely missed in migration.
