### ISSUE TITLE
16.0 tracking_manager breaks CI

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-tools#3111]
for exemple : 
- https://github.com/OCA/server-tools/pull/3106
- https://github.com/OCA/server-tools/pull/3110

CC maintainers : @sebastienbeau, @Kev-Roche
could you take a look ? 

thanks ! 

<code>

====================================================================== 
2024-11-02 02:20:22,747 398 ERROR odoo odoo.addons.tracking_manager.tests.test_tracking_manager: ERROR: TestTrackingManager.test_o2m_update_m2o_indirectly
Traceback (most recent call last):
  File "/opt/odoo/odoo/api.py", line 997, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 171

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/fields.py", line 1161, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo/api.py", line 1004, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.actions.act_window(171,).context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/server-tools/server-tools/tracking_manager/tests/test_tracking_manager.py", line 199, in test_o2m_update_m2o_indirectly
    self.partner.write(
  File "/opt/odoo/addons/snailmail/models/res_partner.py", line 26, in write
    return super(ResPartner, self).write(vals)
  File "/opt/odoo/addons/partner_autocomplete/models/res_partner.py", line 228, in write
    res = super(ResPartner, self).write(values)
  File "/opt/odoo/odoo/addons/base/models/res_partner.py", line 730, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/addons/mail/models/mail_activity_mixin.py", line 241, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 315, in write
    result = super(MailThread, self).write(values)
  File "/__w/server-tools/server-tools/tracking_manager/models/models.py", line 156, in write
    return super().write(vals)
  File "/opt/odoo/odoo/models.py", line 3785, in write
    field.write(self, value)
  File "/opt/odoo/odoo/fields.py", line 4267, in write
    return self.write_batch([(records, value)])
  File "/opt/odoo/odoo/fields.py", line 4288, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo/fields.py", line 4460, in write_real
    comodel.browse(command[1]).write(command[2])
  File "/opt/odoo/addons/mail/models/res_users.py", line 96, in write
    write_res = super(Users, self).write(vals)
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 1692, in write
    res = super(UsersView, self).write(values)
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 1388, in write
    return super(UsersImplied, self).write(values)
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 696, in write
    res = super(Users, self).write(values)
  File "/__w/server-tools/server-tools/tracking_manager/models/models.py", line 156, in write
    return super().write(vals)
  File "/opt/odoo/odoo/models.py", line 3807, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/opt/odoo/odoo/models.py", line 1366, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 569, in _check_action_id
    if not action.context:
  File "/opt/odoo/odoo/fields.py", line 1191, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: ir.actions.act_window(171,), User: 1)
 
</code>

**Comment by legalsylvain** [comment]
fixed by https://github.com/OCA/server-tools/pull/3112 I guess.
