### ISSUE TITLE
Audit log module Break Odoo Uni test

### ISSUE THREAD

**Issue by uynil** [OCA/server-tools#3121]
## Module
Audit log module Break Odoo Uni test

## Describe the bug
Audit log module Break Odoo Uni test

## To Reproduce
**Affected versions**:
17.0
odoo enterprise

1. run odoo unit test ( my system is odoo.sh)
2.
3.

Error log
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/tests/test_reports.py", line 55, in test_report_session_cookie
    mock_request.session.sid = self.authenticate(admin.login, admin.login).sid
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1793, in authenticate
    session.context = dict(env['res.users'].context_get())
  File "<decorator-gen-109>", line 2, in context_get
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/res_users.py", line 809, in context_get
    values = user.read(list(name_to_key), load=False)[0]
  File "/home/odoo/src/user/auditlog/models/rule.py", line 363, in read
    rule_model.sudo().create_logs(
  File "/home/odoo/src/user/auditlog/models/rule.py", line 523, in create_logs
    "http_request_id": http_request_model.current_http_request(),
  File "/home/odoo/src/user/auditlog/models/http_request.py", line 53, in current_http_request
    self.env.cr.execute(
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: can't adapt type 'Mock'

2024-11-18 15:36:37,751 43 ERROR sjfoiew 9978 odoo.sql_db: bad query: SELECT id FROM %s WHERE id = %s
ERROR: can't adapt type 'Mock' 

**Expected behavior**
Pass Unit Test

**Additional context**
Python 3.10
Ubuntu 22.04

**Comment by bouktaibMohssin** [comment]
Hello @uynil , i second this issue i have a similar one as well on odoo.sh
