### ISSUE TITLE
[8.0] Cannot use runbot due to letsencrypt module's python dependency "acme_tiny"

### ISSUE THREAD

**Issue by atchuthan** [OCA/server-tools#430]
Cannot use runbot due to package dependency.  How is this issue resolved usually?

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/service/server.py", line 930, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/modules/loading.py", line 319, in load_modules
    modobj.button_install(cr, SUPERUSER_ID, ids)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/addons/base/module/module.py", line 414, in button_install
    self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/addons/base/module/module.py", line 405, in state_update
    self.check_external_dependencies(module.name, newstate)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147296-8-0-aae74f/openerp/addons/base/module/module.py", line 378, in check_external_dependencies
    raise orm.except_orm(_('Error'), msg % (module_name, e.args[0]))
**except_orm: ('Error', u'Unable to install module "letsencrypt" because an external dependency is not met: No module named acme_tiny')**

cc: @hbrunn

**Comment by pedrobaeza** [comment]
This is logical, because you have to install that python dependency: `sudo pip install acme_tiny`

**Comment by atchuthan** [comment]
yes, I know about the manual installation.  How do we do this in the RUNBOT??

**Comment by atchuthan** [comment]
@pedrobaeza you could see all the failed instances in runbot for 8.0 here: https://runbot.odoo-community.org/runbot/repo/github-com-oca-server-tools-149

**Comment by pedrobaeza** [comment]
OK, sorry. I didn't read well. I have installed it in runbot.

**Comment by atchuthan** [comment]
I tried to rebuild the last instance of 8.0, it says to install IPy python package.
except_orm: ('Error', u'Unable to install module "letsencrypt" because an external dependency is not met: No module named **IPy**')

**Comment by pedrobaeza** [comment]
Installed also.

**Comment by atchuthan** [comment]
thanks @pedrobaeza for resolving the runbot error for 8.0.
