### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by SiriusFuenmayor** [OCA/server-tools#487]
When adding the server-tools directory to my addons path and restarting Odoo I get the following error:

"Could not get content for /base/static/src/css/modules.css"

![error odoo](https://cloud.githubusercontent.com/assets/8355915/17159703/4df6302e-536d-11e6-9361-d2f922fbf075.jpg)

**Comment by SiriusFuenmayor** [comment]
I'm using version 8.0 of Odoo

**Comment by pedrobaeza** [comment]
Please paste here your server log. Be sure you have an up to date version of the repository.

**Comment by SiriusFuenmayor** [comment]
2016-07-27 01:02:24,495 15064 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/sirius/.virtualenvs/odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/sirius/.virtualenvs/odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/sirius/Projects/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/home/sirius/Projects/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/sirius/Projects/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/sirius/Projects/odoo/openerp/http.py", line 1289, in **call**
    self.load_addons()
  File "/home/sirius/Projects/odoo/openerp/http.py", line 1308, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/home/sirius/Projects/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/sirius/Projects/server-tools/base_optional_quick_create/**init**.py", line 5, in <module>
    from . import models
  File "/home/sirius/Projects/server-tools/base_optional_quick_create/models/**init**.py", line 5, in <module>
    from . import ir_model
  File "/home/sirius/Projects/server-tools/base_optional_quick_create/models/ir_model.py", line 6, in <module>
    from openerp.exceptions import UserError
ImportError: cannot import name UserError

**Comment by SiriusFuenmayor** [comment]
![error odoo](https://cloud.githubusercontent.com/assets/8355915/17160791/c7dfd6e4-5375-11e6-9887-778a9c1dd7a5.jpg)

**Comment by moylop260** [comment]
Your log show us: `server-tools/base_optional_quick_create/models/ir_model.py` but our branch 8.0 there isn't the `models` path.
- https://github.com/OCA/server-tools/tree/8.0/base_optional_quick_create

Maybe, You are using 9.0
- https://github.com/OCA/server-tools/blob/9.0/base_optional_quick_create/models/ir_model.py

**Comment by SiriusFuenmayor** [comment]
Thank you, I forget to do git checkout 8.0 after cloning the repository
