### ISSUE TITLE
Error when loading base_user_gravatar

### ISSUE THREAD

**Issue by jalzaga** [OCA/server-tools#538]
When starting odoo the module gives an error and stop the server
Versions affected 9.0

Error log:
2016-08-31 11:38:00,855 23895 DEBUG ? openerp.http: Loading base_user_gravatar
2016-08-31 11:38:00,876 23895 INFO ? werkzeug: 127.0.0.1 - - [31/Aug/2016 11:38:00] "POST /longpolling/poll HTTP/1.0" 500 -
2016-08-31 11:38:00,888 23895 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1492, in **call**
    self.load_addons()
  File "/opt/odoo/odoo/openerp/http.py", line 1513, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/odoo/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/**init**.py", line 6, in <module>
    from . import tests
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/**init**.py", line 2, in <module>
    from . import test_res_users
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/test_res_users.py", line 14, in <module>
    class TestResUsers(TransactionCase):
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/test_res_users.py", line 34, in TestResUsers
    @mock.patch('%s.urllib2' % MODULE_LOCATION)
  File "/usr/share/pyshared/mock.py", line 720, in patch
    target = _importer(target)
  File "/usr/share/pyshared/mock.py", line 514, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/share/pyshared/mock.py", line 504, in _dot_lookup
    return getattr(thing, comp)
AttributeError: 'module' object has no attribute 'base_user_gravatar'
^C
root@h2583882:/opt/odoo/odoo/addons/mail# vi /var/log/odoo/odoo-server.log
2016-08-31 11:38:00,888 23895 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1492, in __call__
    self.load_addons()
  File "/opt/odoo/odoo/openerp/http.py", line 1513, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/odoo/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/**init**.py", line 6, in <module>
    from . import tests
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/**init**.py", line 2, in <module>
    from . import test_res_users
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/test_res_users.py", line 14, in <module>
    class TestResUsers(TransactionCase):
  File "/opt/odoo/OCA/server-tools/base_user_gravatar/tests/test_res_users.py", line 34, in TestResUsers
    @mock.patch('%s.urllib2' % MODULE_LOCATION)
  File "/usr/share/pyshared/mock.py", line 720, in patch
    target = _importer(target)
  File "/usr/share/pyshared/mock.py", line 514, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/share/pyshared/mock.py", line 504, in _dot_lookup
    return getattr(thing, comp)
AttributeError: 'module' object has no attribute 'base_user_gravatar'

**Comment by pedrobaeza** [comment]
You haven't indicated version, but I deduced is 9.0. Fixed in https://github.com/OCA/server-tools/commit/a87ba3a1993e8c1f8af4919fd5ff9530bf89ed36

**Comment by jalzaga** [comment]
That´s right, I did, "Versions affected 9.0".
Thanks for fixing it, now it works

**Comment by pedrobaeza** [comment]
Sorry, I didn't see it between the log. My fault.
