### ISSUE TITLE
Wont work along with crm_duplicates plugin

### ISSUE THREAD

**Issue by luisdanielperezt** [OCA/server-tools#551]
module: server-tools
version: 9.0

**Steps to reproduce**
- i create a lead mass editing button as explained in the tutorial video
  -i try to assign a salesperson to more than one lead using the list_view of leads in odoo

**Current behavior**
-Odoo throws me this error:
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 683, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 312, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 962, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 512, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 897, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/mass_editing/wizard/mass_editing_wizard.py", line 327, in create
    model_obj.browse(self._context.get('active_ids')).write(values)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/website_crm_score/models/crm_lead.py", line 90, in write
    return super(Lead, self).write(vals)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/crm_duplicates/models/lead.py", line 22, in write
    domain = [('id','!=',self.id)]
  File "/home/odoo/odoo-dev/odoo/openerp/fields.py", line 2020, in __get__
    return record.ensure_one()._ids[0]
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 5415, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: crm.lead(318678, 318677)
**Expected behavior**
-Should mass_edit the leads.

**Comment by pedrobaeza** [comment]
server-tools is not a module, but a repository. And if the other module is not from OCA, you cannot post here the problem.

**Comment by luisdanielperezt** [comment]
I already noticed that. Sorry.
