### ISSUE TITLE
[9.0] Letsencrypt challenge fails

### ISSUE THREAD

**Issue by kenneth-vkd** [OCA/server-tools#570]
Hi
For some time we have been using the letsencrypt module with Odoo 9.0 Enterprise.
The instance runs on a seperate server with it's own public IP-address.
At september 6th it was no longer able to renew the certificate. Trying to log in to Odoo and run the cron task manually revealed this in the log file:

```
2016-10-12 07:40:10,947 3871 ERROR myodoo openerp.addons.base.ir.ir_cron: Call of self.pool.get('letsencrypt').cron(cr, uid, *()) failed in Job 7
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/letsencrypt/models/letsencrypt.py", line 151, in cron
    account_key, csr, acme_challenge, log=_logger, CA=DEFAULT_CA)
  File "/usr/local/lib/python2.7/dist-packages/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /var/lib/odoo/.local/share/Odoo/letsencrypt/acme-challenge/iSGC6nbKoJlorYjjGD52iPyUBM6glZXIIreRJQjaQ8Q, but couldn't download http://myodoo.tld/.well-known/acme-challenge/iSGC6nbKoJlorYjjGD52iPyUBM6glZXIIreRJQjaQ8Q
```

In the log output above I have changed any references to the real domain name and database name with `myodoo`.
This is my `/etc/nginx/sites-enabled/default` file:

```
upstream openerp {
        server 127.0.0.1:8069;
}
server {
#       listen 80 default_server;
#       listen 80;
#       listen [::]:80 default_server ipv6only=on;
        listen 443 ssl;
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name myodoo.tld www.myodoo.tld;

        ssl_certificate /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.crt;
        ssl_certificate_key /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

        location / {
                proxy_pass  http://openerp;
                # force timeouts if the backend dies
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                proxy_redirect off;

                # set headers
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto https;
        }

        # Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests
        #location /RequestDenied {
        #       proxy_pass http://127.0.0.1:8080;
        #}

        #error_page 404 /404.html;

        # redirect server error pages to the static page /50x.html
        #
        #error_page 500 502 503 504 /50x.html;
        #location = /50x.html {
        #       root /usr/share/nginx/html;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #       # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        #
        #       # With php5-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php5-fpm:
        #       fastcgi_pass unix:/var/run/php5-fpm.sock;
        #       fastcgi_index index.php;
        #       include fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
        location ~ /.well-known {
                allow all;
        }
}

## http redirects to https ##
server {
    listen      80;
    server_name myodoo.tld www.myodoo.tld;
    if ($scheme = "http") {
        set $redirect_https 1;
    }
    if ($request_uri ~ ^/.well-known/acme-challenge/) {
        set $redirect_https 0;
    }
    if ($redirect_https) {
        rewrite ^   https://$server_name$request_uri? permanent;
    }
}
```

Also trying to access the acme-challenge URI from a web browser returns 404, but nginx configuration works, as the URL is actually served using http and does not redirect to https.
We have just dowloaded the latest code from the github repo this morning to make sure that the issue was not with an outdated version of the code. acme-tiny and IPy were also updated this morning.
What is the issue here?

**Comment by hbrunn** [comment]
if what you posted is your complete configuration, this cannot ever work. The server defined for port 80 will try to serve nginx' default server, because you didn't define anything else there. Make the first server listen to port 80 too, move the redirecting code before your location rule, delete the second server and you should be fine

**Comment by kenneth-vkd** [comment]
If you are refering to these lines of the config file, they are commented out using # 

```
#       listen 80 default_server;
#       listen 80;
#       listen [::]:80 default_server ipv6only=on;
```

But what you say is that I need to change the file to look like this:

```
upstream openerp {
        server 127.0.0.1:8069;
}
## http redirects to https ##
server {
    listen      80;
    server_name myodoo.tld www.myodoo.tld;
    if ($scheme = "http") {
        set $redirect_https 1;
    }
    if ($request_uri ~ ^/.well-known/acme-challenge/) {
        set $redirect_https 0;
    }
    if ($redirect_https) {
        rewrite ^   https://$server_name$request_uri? permanent;
    }
}
server {
#       listen 80 default_server;
#       listen 80;
#       listen [::]:80 default_server ipv6only=on;
        listen 443 ssl;
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name myodoo.tld www.myodoo.tld;

        ssl_certificate /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.crt;
        ssl_certificate_key /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

        location / {
                proxy_pass  http://openerp;
                # force timeouts if the backend dies
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                proxy_redirect off;

                # set headers
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto https;
        }

        # Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests
        #location /RequestDenied {
        #       proxy_pass http://127.0.0.1:8080;
        #}

        #error_page 404 /404.html;

        # redirect server error pages to the static page /50x.html
        #
        #error_page 500 502 503 504 /50x.html;
        #location = /50x.html {
        #       root /usr/share/nginx/html;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #       # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        #
        #       # With php5-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php5-fpm:
        #       fastcgi_pass unix:/var/run/php5-fpm.sock;
        #       fastcgi_index index.php;
        #       include fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
        location ~ /.well-known {
                allow all;
        }
}
```

The strange this is that the above config was working and renewing fine until last month.

**Comment by hbrunn** [comment]
now you did the cleanup consequently, that's less confusing, good. But what I meant is: Make your main configuration listen to port 80, and move the redirecting code in there. So the second commented out line you quoted shouldn't be quoted out, and the redirection take place within this server

**Comment by kenneth-vkd** [comment]
So the final file should look like this?

```
upstream openerp {
        server 127.0.0.1:8069;
}
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;
    server_name myodoo.tld www.myodoo.tld;
    if ($scheme = "http") {
        set $redirect_https 1;
    }
    if ($request_uri ~ ^/.well-known/acme-challenge/) {
        set $redirect_https 0;
    }
    if ($redirect_https) {
        rewrite ^   https://$server_name$request_uri? permanent;
    }
}
server {
        listen 443 ssl;

        server_name myodoo.tld www.myodoo.tld;

        ssl_certificate /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.crt;
        ssl_certificate_key /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

        location / {
                proxy_pass  http://openerp;
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                proxy_redirect off;

                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto https;
        }
        location ~ /.well-known {
                allow all;
        }
}
```

**Comment by hbrunn** [comment]
no, it should look like

```
upstream openerp {
        server 127.0.0.1:8069;
}

server {
    listen 443 ssl;
    listen 80;
    if ($scheme = "http") {
        set $redirect_https 1;
    }
    if ($request_uri ~ ^/.well-known/acme-challenge/) {
        set $redirect_https 0;
    }
    if ($redirect_https) {
        rewrite ^   https://$server_name$request_uri? permanent;
    }
    etc...
}
```

**Comment by kenneth-vkd** [comment]
Okay, now I think that I get it.

```
upstream openerp {
        server 127.0.0.1:8069;
}
server {
        listen 443 ssl;
        listen 80;
        if ($scheme = "http") {
            set $redirect_https 1;
        }
        if ($request_uri ~ ^/.well-known/acme-challenge/) {
            set $redirect_https 0;
        }
        if ($redirect_https) {
            rewrite ^   https://$server_name$request_uri? permanent;
        }
        server_name myodoo.tld www.myodoo.tld;

        ssl_certificate /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.crt;
        ssl_certificate_key /var/lib/odoo/.local/share/Odoo/letsencrypt/myodoo.tld.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

        location / {
                proxy_pass  http://openerp;
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                proxy_redirect off;

                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto https;
        }
        location ~ /.well-known {
                allow all;
        }
}
```

It is not really clear from the documentation on the module that the file should look like this.

**Comment by hbrunn** [comment]
your PR to improve the docs will be appreciated

**Comment by hbrunn** [comment]
I believe the extra location block you added will mess things up, put you'll find that out soon enough

**Comment by hbrunn** [comment]
no need for thanks or following up on the documentation, people just love doing unpaid work for impolite strangers

**Comment by kenneth-vkd** [comment]
I am actually working on an improved documentation for both the current V9 and also for the newly released V10.

**Comment by hbrunn** [comment]
great!
