### ISSUE TITLE
Error trying to install server_environment v8

### ISSUE THREAD

**Issue by kkoci** [OCA/server-tools#690]
Hi, When trying to install the v8 of 'server_environment' module, it throws me this error:

`

Odoo Server Error

Traceback (most recent call last):
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/kristian/odoov8/odoo-8.0-20161017/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/kristian/odoov8/magento-connector/server-tools/server_environment/__init__.py", line 21, in <module>
    from .serv_config import serv_config, setboolean
  File "/home/kristian/odoov8/magento-connector/server-tools/server_environment/serv_config.py", line 41, in <module>
    "The parameter 'running_env' has not be set neither in base config "
Exception: The parameter 'running_env' has not be set neither in base config file option -c or in openerprc.
We strongly recommend against using the rc file but instead use an explicit config file with this content:
[options]
running_env = dev

`

Any clues about this?

**Comment by lasley** [comment]
Hi @kkoci - this error is expected. Please read the [ReadMe config instructions](https://github.com/OCA/server-tools/tree/10.0/server_environment#configuration)
