### ISSUE TITLE
[10.0.1 mass editing]Odoo Server Error when trying to add fields

### ISSUE THREAD

**Issue by arnelap** [OCA/server-tools#789]
The error is displayed when i click "Add An Item" under Fields on Odoo 10.

For example when I want to configure a mass edit for contacts:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 820, in search_read
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 842, in do_search_read
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 4659, in search_read
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1509, in search
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 4205, in _search
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 4006, in _where_calc
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\osv\expression.py", line 1287, in to_sql
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\osv\expression.py", line 1212, in __leaf_to_sql
ValueError: Invalid domain term (u'model_id', u'in', {u'model': u'res.partner', u'transient': False, u'name': u'Partner', u'state': u'base'})

**Comment by pedrobaeza** [comment]
Don't reproduce in runbot, so I close. If you're able to do reproduce it, please put the corresponding steps.
