### ISSUE TITLE
Audit_Log Bug Report

### ISSUE THREAD

**Issue by raycollazo** [OCA/server-tools#822]
We discovered a bug in Audit Log. When creating a Rule for Employee model that includes Read
![auditlogrule](https://cloud.githubusercontent.com/assets/17937809/25468314/156b7694-2ae3-11e7-84b0-f898bcdf47f5.png)
It immediately causes an error and does not allow you to go into a user.
![auditlogruleerror](https://cloud.githubusercontent.com/assets/17937809/25468342/4bd7cd54-2ae3-11e7-8b12-37be03af9717.png)

This error was replicated by simply creating a rule that includes the Read option. I did not try this rule on any other models yet but I can only assume.
Unchecking the read box immediately fixes the issue.

Version was Odoo 10 Enterprise

Here is the Text of the Error:

Traceback (most recent call last):
  File "/opt/Software/Software-server/Software/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Software/Software-server/Software/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Software/Software-server/Software/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Software/Software-server/Software/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Software/Software-server/Software/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Software/Software-server/Software/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/Software/Software-server/Software/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/Software/Software-server/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/Software/Software-server/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Software/Software-server/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/Software/Software-server/Software/api.py", line 670, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/opt/Software/Software-server/Software/models.py", line 4881, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 23; 2 is required

**Comment by MartinHeisig** [comment]
The same with Odoo Community Edition.

Created a rule for res.partner without "read"-option and all fine. Adding the "read"-option causes a big delay while opening res.partner list view and causes error while selecting a single partner entry. And in four out of five tries (no idea why it works one time) changing or deactivating or deleting the rule doesn't do anything, it still logs and gives this error. Only deinstall and reinstall the module helps in this case.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/api.py", line 670, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/usr/lib/python2.7/dist-packages/Software/models.py", line 4890, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 14; 2 is required
