### ISSUE TITLE
[10.0] Module not completely uninstalled. Left a non-working menu in Task Management

### ISSUE THREAD

**Issue by arafatx** [OCA/server-tools#850]
After uninstall the module from the app list, there is a non-working menu in Task Management (screenshot attached). When clicking on the menu, the following message appear:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 1152, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/usr/lib/python2.7/site-packages/odoo/addons/project_model_to_task/models/project.py", line 95, in read
    res = super(IrActionActWindows, self).read(fields=fields, load=load)
  File "/usr/lib/python2.7/site-packages/odoo/addons/partner_contact_in_several_companies/models/ir_actions.py", line 12, in read
    actions = super(IRActionsWindow, self).read(fields=fields, load=load)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 317, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3021, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 981, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 277, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 752, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 174, in __getitem__
    return self.models[model_name]
KeyError: u'auditlog.log'

![pppp](https://user-images.githubusercontent.com/4420157/26860183-291f8a3e-4b6f-11e7-85ee-7937dc1e6ea5.PNG)

How do I completely remove this one.

Step to reproduce:

1) Install audit_trail app.
2) Remove it.
3) Look at the Task 'Action' menu there is a menu call 'View Log' created by audit_trail which is not removed after uninstall.
4) Click on the 'View Log' menu and error appears.

**Comment by pedrobaeza** [comment]
It seems you have to remove the menu (that you added at first instance) before uninstalling the module.

**Comment by CasVissers-360ERP** [comment]
I also faced the same issue in v13 ir.actions.act_window are not removed when uninstalling the module which results in this traceback. Can be tricky.
