### ISSUE TITLE
Mass Editing v10

### ISSUE THREAD

**Issue by mariothiermann** [OCA/server-tools#864]
I try to mass edit the many2many field public_categ_ids in product_template.

It works proper if i choose one record but if i choose more then one the following error appears.

```
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/mass_editing/wizard/mass_editing_wizard.py", line 253, in create
    model_obj.browse(self._context.get('active_ids')).write(values)
  File "/odoo/custom/addons/product_bundle_pack/models/product.py", line 65, in write
    if self.cal_pack_price:
  File "/odoo/odoo-server/odoo/fields.py", line 863, in __get__
    record.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 4797, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.template(13, 14, 15)
```

Actually i just need mass editing, how the name says, for many records.

**Comment by pedrobaeza** [comment]
Please put complete stack trace.

**Comment by mariothiermann** [comment]
Ok got it. i deinstallad the module for product bundle and it works like it should.

Thank you for answering
