### ISSUE TITLE
Unable to install "Verify email at signup"

### ISSUE THREAD

**Issue by puakinsin** [OCA/server-tools#884]
I have installed validate_email with the following command 
$ sudo pip install validate_email

and when I tried to install the module the following traceback popped up

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 777, in _tag_template
    return self._tag_record(record, data_node)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_model.py", line 1228, in _update
    record = record.create(values)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 360, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3838, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 1000, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 378, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3715, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<xpath expr="//div[@class='form-group field-password']">' cannot be located in parent view

Error context:
View `signup_fields`
[view_id: 2511, xml_id: n/a, model: n/a, parent_id: 280]
None" while parsing None:6, near
<data inherit_id="auth_signup.fields">
    <xpath expr="//div[@class='form-group field-password']" position="attributes">
        <attribute name="t-if">only_passwords</attribute>
    </xpath>
    <xpath expr="//div[@class='form-group field-confirm_password']" position="attributes">
        <attribute name="t-if">only_passwords</attribute>
    </xpath>
    <xpath expr="//input[@name='login']" position="attributes">
        <attribute name="type">email</attribute>
    </xpath>
</data>
```

**Comment by pedrobaeza** [comment]
You have other module that modifies signup/login screen and it's incompatible with this one. Try on a fresh DB and you will see it installs.
