### ISSUE TITLE
Base_import_match v9: Cannot create new import match in settings

### ISSUE THREAD

**Issue by wim-a** [OCA/server-tools#900]
I installed base_import_match on Odoo 9E. When I try in the settings to create a new import match, and I want to select the model, I get the following error message:

```
Traceback (most recent call last):
  File "/home/odoo/new/odoo9/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/new/odoo9/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/new/odoo9/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/new/odoo9/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/new/odoo9/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/new/odoo9/enterprise/web/controllers/main.py", line 910, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/new/odoo9/enterprise/web/controllers/main.py", line 902, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/models.py", line 1749, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/odoo/new/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/new/odoo9/openerp/addons/base/ir/ir_model.py", line 121, in _name_search
    super(ir_model, self).search(cr, uid, domain, limit=limit, context=context),
  File "/home/odoo/new/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/models.py", line 1668, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/new/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/models.py", line 4793, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/home/odoo/new/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/new/odoo9/openerp/models.py", line 4564, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/home/odoo/new/odoo9/openerp/osv/expression.py", line 644, in __init__
    self.parse(cr, uid, context=context)
  File "/home/odoo/new/odoo9/openerp/osv/expression.py", line 844, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field u'transient ' in leaf "<osv.ExtendedLeaf: (u'transient ', u'=', False) on ir_model (ctx: )>"
```

**Comment by yajo** [comment]
Fix in https://github.com/OCA/server-tools/pull/901, closing here to track progress there.
