### ISSUE TITLE
[10.0][password_security] Internal server error on wrong login

### ISSUE THREAD

**Issue by hmrodrigues** [OCA/server-tools#914]
Having the module password_security installed, if a login is incorrect, instead of showing the wrong login message, it shows a internal server error.

Steps to reproduce:
- On Odoo 10, install password_security
-  Log off and log in with a incorrect combination

Expected
- On a wrong login, show the  **Wrong login/password** message

Best Regards,
Hugo Rodrigues

**Comment by lasley** [comment]
Hi @hmrodrigues - There is no `password_policy` module that I know of. Do you mean `password_security`?

**Comment by hmrodrigues** [comment]
@lasley yes sorry my bad. I fixed the title and issue

**Comment by lasley** [comment]
@hmrodrigues Hmmmm it's working fine for me on Runbot. On a hunch, I installed `website` & was then able to replicate the issue.
```
2017-07-30 17:33:04,969 167 WARNING openerp_test odoo.addons.auth_brute_force.controllers.main: Authentication failed from remote '172.17.42.1'. Login tried : 'asdfsd'. Attempt 1 / 10.
2017-07-30 17:33:05,221 167 ERROR openerp_test odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
File "/home/odoo/odoo-10.0/addons/website/models/ir_http.py", line 273, in _handle_exception
response = super(Http, cls)._handle_exception(exception)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
return request._handle_exception(exception)
File "/.repo_requirements/odoo/odoo/http.py", line 768, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
result = request.dispatch()
File "/.repo_requirements/odoo/odoo/http.py", line 827, in dispatch
r = self._call_function(**self.params)
File "/.repo_requirements/odoo/odoo/http.py", line 333, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/.repo_requirements/odoo/odoo/service/model.py", line 101, in wrapper
return f(dbname, *args, **kwargs)
File "/.repo_requirements/odoo/odoo/http.py", line 329, in checked_call
result.flatten()
File "/.repo_requirements/odoo/odoo/http.py", line 1259, in flatten
self.response.append(self.render())
File "/.repo_requirements/odoo/odoo/http.py", line 1252, in render
return env["ir.ui.view"].render_template(self.template, self.qcontext)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1039, in render_template
return self.browse(self.get_view_id(template)).render(values, engine)
File "/home/odoo/odoo-10.0/addons/website/models/ir_ui_view.py", line 110, in render
return super(View, self).render(values, engine=engine)
File "/home/odoo/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
return super(IrUiView, self).render(values=values, engine=engine)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1059, in render
return self.env[engine].render(self.id, qcontext)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
self.compile(template, options)(self, body.append, values or {})
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
raise e
QWebException: Expected singleton: res.users[]
Traceback (most recent call last):
File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
return compiled(self, append, values, options, log)
File "<template>", line 1, in template_website_layout_475
File "<template>", line 3, in body_call_content_474
File "<template>", line 18, in set_456
File "/.repo_requirements/odoo/odoo/addons/base/res/res_users.py", line 571, in _is_superuser
self.ensure_one()
File "/.repo_requirements/odoo/odoo/models.py", line 4826, in ensure_one
raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.users[]

Error to render compiling AST
ValueError: Expected singleton: res.users[]
Template: website.layout
Path: /templates/t/t/t[5]/script/t
Node: <t t-esc="json.dumps(request.env.user._is_superuser())"/>,
is_frontend: true,
```

**Comment by nguyenductamlhp** [comment]
Hello @lasley, I have tried your glue module and it was still error with Live Chat module.
I try to fix this error in [this](https://github.com/OCA/server-tools/pull/938)
