### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 20; 2 is required

### ISSUE THREAD

**Issue by anniquetapha** [OCA/server-tools#924]
module: auditlog
version: 10.0

**Steps to reproduce**
- ...When i create a read audit on a model, and i try to read open the records in that model, it gives me "Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 885, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 877, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 681, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 670, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 4890, in with_context
ValueError: dictionary update sequence element #0 has length 20; 2 is required"

**Current behavior**
The error above pops up
**Expected behavior**
It should allow me to open the record without problems

**Comment by nikeshscs** [comment]
Hello,
module: auditlog  (https://apps.odoo.com/apps/modules/10.0/auditlog/)
version: 10.0 CE
I'm facing the same problem with auditlog module.
Below zip is video clip that shows the how that error is produce.

[auditlog-2019-06-03_17.39.16.zip](https://github.com/OCA/server-tools/files/3246933/auditlog-2019-06-03_17.39.16.zip)

Thanks.
